### ISSUE TITLE
Fire Blockstates ( east north south up west ) Don't produce light

### ISSUE THREAD

**Issue by zndrmn** [gri573/rethinking-voxels#1]
What normal fire looks like

![2022-10-15_15 05 12](https://user-images.githubusercontent.com/77690119/196005689-26f57a12-1019-4013-9207-e0f19695a497.png)

What fire blockstates looks like

![2022-10-15_15 05 22](https://user-images.githubusercontent.com/77690119/196005688-996d4fe3-9f31-4b48-80a2-ff909f31dc66.png)
![2022-10-15_15 05 17](https://user-images.githubusercontent.com/77690119/196005691-46e7bf7c-5c6a-4428-be79-ba6d60289e97.png)

**Comment by gri573** [comment]
fixed on commit [f810842](https://github.com/gri573/rethinking-voxels/commit/f810842b316d9eff2e3d04ec59b302c6b26e92ed) (I hope)
