### ISSUE TITLE
Suggestion: Some form of utility for adding modded blocks.

### ISSUE THREAD

**Issue by Dryym** [gri573/rethinking-voxels#10]
It would be really nice if there were some kind of included utility to create a modded block property file. Currently, One would have to manually put every block ID into the block.properties file. Which quickly becomes unwieldy and impractical with multiple mods. Even a utility which just gets a list of every block ID as plaintext would speed up the process massively.

I'm not expecting things to work flawlessly. It'd just be nice to have an easier way to keep shadows from *completely* breaking with modded blocks.

**Comment by gri573** [comment]
That's way outside of the scope of a shaderpack. asking mod developers to provide block ID lists would probably be a good approach for that
