### ISSUE TITLE
Emmise mobs

### ISSUE THREAD

**Issue by goobtheboob** [gri573/rethinking-voxels#101]
It seems that the some mob's emissions are inverted; the parts that shouldn't be glowing are, vise versa.
It is something to do with the "Integrated PBR" setting.
Here is a pic of it:
![bug](https://user-images.githubusercontent.com/98430746/224438329-40430263-d53a-4fe8-9104-dbb03c0fc783.jpg)
(The mobs in the pic is just a resource pack that I had made)

**Comment by gri573** [comment]
custom model resource packs are not supported by this shader due to internal limitations
