### ISSUE TITLE
Emissives and item dynamic lights

### ISSUE THREAD

**Issue by LunaMagnoliid** [gri573/rethinking-voxels#102]
All particle emissives, emissives added by resource packs and item dynamic lights don't work.
From what I understand, these are just limitations or not yet implemented, correct? 
Although I'm surprised that _none_ of the particles are emissive despite naturally emissive entity and block textures working fine

![2023-03-12_04 58 03](https://user-images.githubusercontent.com/93735702/224536921-d6f87aa6-fb92-450a-ae52-abf2ea1bac8a.png)
![2023-03-12_05 07 36](https://user-images.githubusercontent.com/93735702/224536922-4fd5b2d1-3cb7-4744-8d6c-7dc08bec7b4f.png)
![2023-03-12_05 07 39](https://user-images.githubusercontent.com/93735702/224536920-78aa0a4d-1e7d-404c-8740-4941208aeffb.png)

**Comment by gri573** [comment]
correct, emissive particles won't light up their surroundings (that's roughly impossible with my method of doing lighting as far as I can tell). They should be able to be lit correctly though.
optifine-format resource pack emissives, however, are completely unsupported (there is no way for the shader to distinguish between things high (vanilla) light map values and optifine emissives), you can use labPBR or seusPBR resource packs instead

**Comment by GALAGOLD** [comment]
Das heißt, es ist unmöglich, Fackeln und brennende Pfeile dynamisch zu beleuchten?

**Comment by gri573** [comment]
torches have their usual geometry (i.e. the actual torch), which allows the shader to give it emission. Fire arrows are more difficult, but not fundamentally impossible to implement

**Comment by gri573** [comment]
I won't do this in the foreseeable future
