### ISSUE TITLE
Lightning bug

### ISSUE THREAD

**Issue by Szigabor07** [gri573/rethinking-voxels#103]
Hi. If i fly or just go up in a cave the moon or the sun shines through the blocks.

**Comment by ankalagon990** [comment]
I am experiencing this as well. In a fresh forge pack with only oculus and rubidium installed (example: https://youtu.be/h0PcBYkxHVY ), in the normal MC Launcher with optifine; similar results (example: https://youtu.be/kNBoQF87MC8 ). 

In forge I get the same glitch with the shadows of mobs being rendered over everything, with optifine I get similar results but it doesn't look like it's just mob shadows that are affected. In both cases the shadows move in relation to the player. I've tried this with multiple versions (beta 17-18c) and always get the same or very similar results.

**Comment by gri573** [comment]
which version do you use?

**Comment by F0XEYE** [comment]
I was using version 18c today and the same thing is happening to me. (All default settings)

**Comment by TheOtherMLG** [comment]
I just set my preset to low, and that fixed it.

**Comment by SJK9906** [comment]
try to use iris or change the shaders setting

**Comment by gri573** [comment]
fixed in the latest versions
