### ISSUE TITLE
spruce trees dont look right

### ISSUE THREAD

**Issue by emceeweeb** [gri573/rethinking-voxels#106]
![2023-03-14_16 43 35](https://user-images.githubusercontent.com/124476668/225132170-bcbd93a4-1160-49bf-9e41-5ae3af54743e.png)
i last time i had this issue was with texture packs but it just dosent work

**Comment by gri573** [comment]
what are your in-world coordinates? does it flicker between this state and a correct state?

**Comment by gri573** [comment]
should be fixed in the rewrite even though I don't know what caused it
