### ISSUE TITLE
How can I add light which don't have texture?

### ISSUE THREAD

**Issue by Elaski6573** [gri573/rethinking-voxels#107]
![image](https://user-images.githubusercontent.com/114150904/225187672-c5159897-0cb2-40bb-b1b5-dc16c422e1bb.png)

Most of light source are block like torch and glostone.
But some of block don't have any texture.

Here is an example.
![image](https://user-images.githubusercontent.com/114150904/225189546-8d91ca68-1d49-4f1d-8771-45ac29b08601.png)

This is star flare from blue skies. 
It doesn't have any texture but only particles.
Then how can I add light?

**Comment by DarianLStephens** [comment]
You can't, it's a limitation of how the shader gets its data.
No texture, no data passed to the shader.
The same problem applies to vanilla light blocks, which a surprising amount of people have complained about.

**Comment by gri573** [comment]
yes, that's not possible as explained above
