### ISSUE TITLE
Brightness affected by resolution in Ultra profile

### ISSUE THREAD

**Issue by WigglePig** [gri573/rethinking-voxels#109]
I decided to test these shaders out for the first time today, and I've been really impressed with them.  However, I noticed that while using the Ultra preset, the brightness goes down when using lower resolutions.  This isn't a huge issue, as it looks fine in 1440p.  It may look extremely bright for 4k users, though.  I am using an RTX 2070 Super, with Iris 1.2.6 in version 1.19 of Minecraft.  Here is what it looks like in game for me:

### 1440p
![image](https://user-images.githubusercontent.com/67275842/226205065-2d280c6c-ba18-4c6d-8b9a-bf3fbf18bf7e.png)

### 720p
![image](https://user-images.githubusercontent.com/67275842/226205144-9712a39f-2901-42a9-b165-426fd7266df3.png)

**Comment by gri573** [comment]
rethinking voxels needs at least iris 1.4 or optifine G8 (not sure about optifine) for full functionality.
