### ISSUE TITLE
Suggestions: Light transfer related options.

### ISSUE THREAD

**Issue by Dryym** [gri573/rethinking-voxels#11]
A couple suggestions regarding some configuration options for light transfer.

1: A configuration option to make the size of a light source extend one voxel past the size of the actual block when advanced light transfer is enabled. The reason being that if a light emitting block is flush with a wall, It does not currently behave as one would expect with vanilla lighting. I believe most people would prefer that a light source flush with a wall would light up the wall as well as everything around it.
![2022-12-22_16 35 38](https://user-images.githubusercontent.com/79935070/209231111-13abafb1-fc95-4a47-9b36-f68e9f04737a.png)
vs
![2022-12-22_16 39 13](https://user-images.githubusercontent.com/79935070/209230928-82e8383b-5b9c-4b4c-b3f9-5003221226c2.png)

2: It would be nice if structure void blocks behaved as invisible light occluding blocks. The reason being that they are invisible blocks which are intangible to players and do not have a function in normal builds. This makes them a perfect candidate to be repurposed for allowing players to control light in their builds. This ties in to 

3: It would be nice if light blocks worked. I am not sure if this is an oversight or a technical limitation. However since I was unable to make light blocks work using the block.properties file, I feel as though it is simply not implemented at the moment.

4: Indirect lighting would be a very nice option to have. I think it could be optimized significantly by having indirect lighting use a larger voxel scale than direct lighting. Perhaps a good effect could even be accomplished by just replicating vanilla style per block lighting with each directly lit block acting as a light source.

**Comment by gri573** [comment]
1 would lead to massive amounts of light leaking
2 and 3 are impossible because the shader can only get information about things that have rendered geometry
4 will only happen on a per-block level, if at all. It is possible, but I don't know how it would affect performance and I don't personally miss it when playing, so it's kind of low priority at the moment. it is probably easier to implement with basic light propagation
