### ISSUE TITLE
Chunk doesn't display correctly

### ISSUE THREAD

**Issue by Elaski6573** [gri573/rethinking-voxels#110]
Inside the cave, If there is a height difference, I cannot see a specific chunk.

![image](https://user-images.githubusercontent.com/114150904/226592973-b5bf36cc-bdd5-4fb0-af59-6098387b31d2.png)

![image](https://user-images.githubusercontent.com/114150904/226593745-3bd53722-4f88-4ac6-a8fe-147a1ca81194.png)

I can see glowing squid above the chunk.

**Comment by Bipbip2109** [comment]
Isn't this a normal Minecraft bug?

**Comment by gri573** [comment]
this is a minecraft bug, there's nothing a shader can do about it
