### ISSUE TITLE
Real time shadow moving randomly

### ISSUE THREAD

**Issue by Tragaf** [gri573/rethinking-voxels#112]
Hey, i just installed the shader and it looks pretty nice.
But, when i move the shadows are moving pretty randomly and its really not smooth.
What should i do ?
I'm using a RX6800 with a R7 5800X if it can help
Last optifine and forge version

There's a video where you can see what's happening
https://user-images.githubusercontent.com/128726979/227264661-10f099d0-40f3-4f44-88b6-c2b5a366a6c7.mp4

**Comment by gri573** [comment]
This looks like it could be fixed by setting blocklight shadow mode to partial, but it should still not happen even with it set to full

**Comment by jvpts11** [comment]
i'm having the same issue, i'm using an RTX 2060 and a i5 12600k

**Comment by Magica427** [comment]
Same problem here with ADM, i tried changing blocklight shadow mode but it did not fix it

**Comment by Magica427** [comment]
Found a fix, i changed the profile to HIGH from CUSTOM and it fixed it

**Comment by ItsMasterL** [comment]
I have not been able to fix this, even with changing the profile, i had to disable realtime shadows which is a shame

**Comment by gri573** [comment]
this will be fixed in the next major version

**Comment by Tragaf** [comment]
Hey sorry for didn't update, i fixed the problem by switching forge and optifine to fabric and iris its  working well now

**Comment by Magica427** [comment]
switching from optifine fixes most issues with advanced mods and shaders

**Comment by BlackWarrior2004** [comment]
> I have almost the same issue, but I think it's from some of the water shadows being reflected in the sky and then in the land because some of the shadows have shape and movement like squids or other animals added by alexmobs (orcas, whales, dolphins)

same is also happening to me
