### ISSUE TITLE
Rebalancing sun light strength?

### ISSUE THREAD

**Issue by Alem95** [gri573/rethinking-voxels#114]
I love this shader, but I've noticed that the difference in intersity between artificial light sources and the sun seems to be very small, resulting in even weak light sources like redstone torches competing with the sun. I assume this is in order to avoid highlights being too bright, but I think a different and more realistic approach could be adding a small amount of auto exposure and increasing the dynamic range of the player camera in the tonemapping, which would allow setting the sun and sky to a much higher brightness level.

I've made some tests and here are the results (before/after)
![2023-04-01_14 55 41](https://user-images.githubusercontent.com/9271144/229291129-f9180e76-0413-478d-8d3f-d40b96717a1d.png)
![2023-04-01_14 55 26](https://user-images.githubusercontent.com/9271144/229291137-05b37bd1-dc1c-4ea0-8e0a-cb638660bb15.png)

![2023-04-01_14 57 19](https://user-images.githubusercontent.com/9271144/229291216-8087bd7c-7bae-47d9-8ea0-75d9671f2390.png)
![2023-04-01_14 57 30](https://user-images.githubusercontent.com/9271144/229291218-f3bca8f5-e035-4342-8c9d-b193262e6958.png)

![2023-04-01_14 57 56](https://user-images.githubusercontent.com/9271144/229291249-b8b528dd-8707-407d-9148-81bedc0e733e.png)
![2023-04-01_14 57 45](https://user-images.githubusercontent.com/9271144/229291251-3496d1dd-3f85-4730-a3d2-99b89955e505.png)

I would create a pull request, but I've never written a shader in my life and I have no idea what kind of other effects the variables I edited and the changes I made to the shaders have created

**Comment by gri573** [comment]
Complementary reimagined, and by consequence rethinking voxels, is balanced around not needing autoexposure. this results in a relatively low dynamic range, and hence, similar brightnesses of light sources. I think that throwing off that balance would hurt the overall visuals, and coming from my experience providing support for people using complementary shaders, I deem the notion of giving people off-by-default settings that may break the visuals in some way unfavourable. However, if you wish to play with brighter sun light, you can multiply [this value](https://github.com/gri573/rethinking-voxels/blob/5ff62a3435434475a8faf69170034ef71b7c5832/shaders/lib/colors/lightAndAmbientColors.glsl#L41) with a number that you like and reload the shader with `R` if on iris, or `F3+R` if on optifine to see your change.
