### ISSUE TITLE
Lava / Clouds lighting problem

### ISSUE THREAD

**Issue by Reattention** [gri573/rethinking-voxels#115]
Lava is an absolute blinding white dot like the sun in outer space
Clouds shadows keep changing every time my character moves an unit

**Comment by gri573** [comment]
if you are using optifine:
please don't touch the shader settings that appear in the shader selection menu. Those are a remainder from times when shaders were not able to create their own options menus yet, and break modern shaderpacks. (see #108 ). Did you change those, and if you did, does resetting them fix the lava problem?
about the cloud shadows: those are probably not cloud shadows, but instead a manifestation of #70

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/229419578-492d4009-b2f6-437e-ab8d-380c15a3e87d.png)
On ultra preset that comes with the shader
![2023-04-03_08 33 10](https://user-images.githubusercontent.com/95251679/229419850-aa2a3199-66fb-467e-88d0-93a725184d59.png)
default preset

**Comment by Reattention** [comment]
![2023-04-03_08 45 13](https://user-images.githubusercontent.com/95251679/229421623-2a81ce12-609a-458b-a3af-db3105c9f400.png)
These are all lava pits

**Comment by Reattention** [comment]
Sorry for the spam, 

https://user-images.githubusercontent.com/95251679/229422742-527b41b8-f383-4cdb-928a-0e78fecc242e.mp4

**Comment by gri573** [comment]
sorry, I was wrong about  the location of the anisotropic filtering setting. It is somewhere else in the video settings, probably in the "other" tab

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/229473405-a7993660-a8e4-42d1-ae8c-1a39e6396df4.png)
![image](https://user-images.githubusercontent.com/95251679/229473449-30c1e299-e2c6-4561-a165-0fa0a795600d.png)
![image](https://user-images.githubusercontent.com/95251679/229473478-cd0a8f06-e0d6-43dc-a409-96b8c407c33a.png)
![image](https://user-images.githubusercontent.com/95251679/229473541-f6ac2bec-60c9-409f-8260-f56c24b66cb8.png)
![image](https://user-images.githubusercontent.com/95251679/229473612-8866ece0-a8f4-45ab-bf7e-2319b5e56335.png)
![image](https://user-images.githubusercontent.com/95251679/229473641-395e321a-2d25-4939-b99b-f8078fd863c3.png)
Some of the settings, lotta pics tho

**Comment by DarianLStephens** [comment]
They could mean the regular Optifine settings, not shader settings.

**Comment by gri573** [comment]
precisely

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/229597748-59d2ca70-8439-4d77-af5a-cd23862930f8.png)
![image](https://user-images.githubusercontent.com/95251679/229597770-23068643-2fdb-41eb-bbeb-505f856542f8.png)
![image](https://user-images.githubusercontent.com/95251679/229597786-23c9bcc3-c9b5-41dd-97d8-cfbf8367f428.png)
![image](https://user-images.githubusercontent.com/95251679/229597814-92dd9cec-fc13-4125-b9f2-94f6806d5503.png)

**Comment by gri573** [comment]
the one I'm looking for is "anisotropic filtering" in the "other" tab.

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/229878457-9984c4d2-4e04-44e1-a054-793196024d70.png)

**Comment by Reattention** [comment]
I fixed it by clicking on the reset video settings

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/229881365-92181d28-19e1-489c-a8d1-2febce63a43c.png)
this is new
![image](https://user-images.githubusercontent.com/95251679/229881391-03d0ad77-5067-4418-876b-96697938b96c.png)

W / O torch
