### ISSUE TITLE
Torches don't work?

### ISSUE THREAD

**Issue by violetpage** [gri573/rethinking-voxels#116]
Hello. Everything looked amazing until I went into a cave. The light worked just fine when I was holding it, but when I placed the torch there wasn't any light emitting from it. I tried messing around with the settings for an hour but nothing seemed to fix it.

**Comment by gri573** [comment]
if you are using optifine: did you set shadow quality to something other than 1x? could you send a screenshot of your F3 debug menu?

**Comment by gri573** [comment]
actually, please continue in #113 , this is probably a duplicate of that
