### ISSUE TITLE
Grainy Shadows

### ISSUE THREAD

**Issue by MattRox989** [gri573/rethinking-voxels#117]
Shadows cast from blocklight look like [this.](https://i.imgur.com/645DFJp.pngl) Is this intentional?

**Comment by Reattention** [comment]
Same. Found a fix?

**Comment by Reattention** [comment]
![image](https://user-images.githubusercontent.com/95251679/230720784-ffa27d4c-a77f-4256-b1c2-fbc2ee894991.png)

**Comment by Sami-channn** [comment]
if you put shadow volume on block light shadow mode it fixes it for me

**Comment by Reattention** [comment]
It does fix the problem but also makes the game uglier

**Comment by Reattention** [comment]
This is with Per Pixel
![image](https://user-images.githubusercontent.com/95251679/230756912-a25100e6-9294-49dc-b1c2-7072b9b22635.png)
this is with shadow mode 
![image](https://user-images.githubusercontent.com/95251679/230756921-156e6bc6-97a1-42c4-81fd-bf483f44aef2.png)

Its like going from LCD to Oled. The black is darker and more precise

**Comment by gri573** [comment]
this is how it is supposed to look, as I prefer grainy shadows over a denoiser that creates a blur. I have plans for a very light denoiser that doesn't cause much blur, it should be in one of the next versions

**Comment by Reattention** [comment]
Okay please update us in here so we can get the notification !

**Comment by scubamount** [comment]
> Shadows cast from blocklight look like [this.](https://i.imgur.com/645DFJp.pngl) Is this intentional?

as stated this is intentional. Please close this issue. You can try upping the vol res or turn on the per pixel setting for better results.
