### ISSUE TITLE
5-30 seconds stuttering upon world changes / new chunks loading.

### ISSUE THREAD

**Issue by NyaomiDEV** [gri573/rethinking-voxels#119]
Just to track it here, and to see if it's a "me" issue or a shared issue.

## First, let's break down the setup
- AMD Radeon RX 6900 XT
- on Windows (11)
- using the AMD drivers version 23.3.2
- using Iris 1.6-pre1, but the exact same issue was there in 1.5.2 as well as the 1.6 betas
- using Minecraft 1.19.4

Also, this issue completely disregards any "preset" and any specific shader configuration. It is present regardless.

## The symptom
The shader loads and plays mostly fine; however, it tends to lag the entire instance (to the point of Minecraft straight up not responding) for periods ranging between 5 to 30 seconds. This can be triggered at any stage in the gameplay, but it is more evident when:
- Joining a new game session, then looking around;
- Activating doors, pistons pushing blocks, or anything which updates the world and consequently reveals a new area, such as a room in a house or an open space from a closed space (leaving a house);
- Adding new lights and blocks to a given scene.

It seems to be related to world-space updates, but I don't know anything about that kind of stuff so I'll leave that to more competent people.

## Logs?
There don't seem to be any logs when those stutters manifest themselves.

**Comment by gri573** [comment]
I am not experiencing that, but I also received a similar report via discord (also using an AMD 6000 series gpu on windows). It may be caused by me writing uninitialised data somewhere, but as it was only reported recently, it may also be related to a new driver version being terribly slow in some very specific case.

**Comment by scubamount** [comment]
+1 experiencing this as well

**Comment by gri573** [comment]
I am now also experiencing this, but the underlying issue is almost certainly a different one
