### ISSUE TITLE
suggestion for light leak in caves

### ISSUE THREAD

**Issue by lingoban** [gri573/rethinking-voxels#120]
Is it will be possible to make something like: when you go below for example coordinate y 60-50 shader will turn off sun light and replace it with normal shadows and light from complementary reimagined, but blocks like lava, torches, etc. will still have rethinking voxels light

**Comment by gri573** [comment]
that will break on superflat worlds or datapack worlds with a changed sea level, and it is also possible to have sunlight fall into a cave as deep as y=0, which creates beautiful-looking light shafts, so I won't be doing that.
