### ISSUE TITLE
Lava is blinding white

### ISSUE THREAD

**Issue by superdeadspace** [gri573/rethinking-voxels#122]
![2023-04-09_19 51 49](https://user-images.githubusercontent.com/59935567/230802275-e9e30fe5-5569-4b5e-a1b6-c50b2f55f025.png)

**Comment by TRYTRY2222** [comment]
at my pc lava is working fine also your water is looking diffrent are you sure you have the correct shader on?

**Comment by gri573** [comment]
pleas reset your video settings, this is a duplicate of #108
