### ISSUE TITLE
Weird (unexpected) shadow and light behavior 

### ISSUE THREAD

**Issue by KevinDellatore** [gri573/rethinking-voxels#124]
Here is an image: https://imgur.com/a/9PXIvmh (let me know if you want it on another hosting site)

I haven't done a significant amount of testing and troubleshooting to figure out if a setting is causing this or not, the only settings I have changed are some of the PBR and normal map settings, and adding emissions to ore blocks and material blocks. Here is a description of the problems I am facing, in the order of the photos: 

1. Sometimes when placing a block (I don't know if its specifically the emissive blocks or any block) shadows cast by the player will seemingly glitch out. You can see in pic 1 that the sun is casting a shadow from my player model but that shadow isn't what I would expect, in the given screenshot it looks like 3 blocks placed in an L shape. When I look/move around the shadow will rapidly change from this shape to a straight line and back again and it looks random. 

2. When the above glitch is occurring if I place or hold a light source, typically a torch or lantern while in a dark environment like a cave or closed building, the dynamic torch light in my hand will flicker and often stop emitting light as I look around. If I look down I can consistently get the light to be completely blocked. It seems like the player model is directly blocking the light from being cast.

3. similarly, when a light source is placed, standing too close to it will block the light from being cast in all directions. 

I don't know if this is normal behavior for this shader pack or if I have some settings enabled that are causing light and shadows to behave this way. I can get the glitch to stop, at least temporarily by setting the time to night, then back to day again. 

Any help or clarification would be greatly appreciated. 

Note: I am using Iris and Sodium (with fabric)

**Comment by gri573** [comment]
I have a suspicion that block IDs have somehow changed in iris 1.6+, I'm not sure if this is an iris bug though, or a bug with my block ID handling that only surfaced because of the different handling. That would explain why the shader doesn't ignore the player when calculating shadows.

**Comment by KevinDellatore** [comment]
It may have something to do with me flying about. I have yet to find the issue in a survival world, but by messing around with blocks in creative super flat worlds, I can consistently recreate the problem. As I said, I haven't had the issue in a survival world, but I haven't had the resources to mess with sea lanterns, emerald blocks, so that could be why.

**Comment by SJK9906** [comment]
i have this problem after pausing and resuming games

#147
#145

**Comment by SJK9906** [comment]
i have this problem while seeing in a direction with all light source
i don't know the position, watch video 

Uploading 2023-05-01 20-41-18.mp4…

**Comment by SJK9906** [comment]
i have this problem while seeing in a direction with all light source
i don't know the position, watch video

https://user-images.githubusercontent.com/129201282/235514692-833fd39c-29b6-4d1e-8f48-3527194e1017.mp4

**Comment by gri573** [comment]
this should now all be fixed hopefully
