### ISSUE TITLE
MC 1.19.4 support

### ISSUE THREAD

**Issue by Polda18** [gri573/rethinking-voxels#125]
I wanted to try the shaders out, but came to find it crashes my game. And I found out why: the latest version (Beta 18c) is still on MC 1.19.2 and 1.19.3, no 1.19.4 support, and I am using Fabric for MC 1.19.4, with Iris 1.5.2. Please add MC 1.19.4 support.

**Comment by KevinDellatore** [comment]
hmm it doesn't crash my game and Im running on the sodium, iris, and fabric package for 1.19.4, some weird shadow behaviors but that's it.

**Comment by Polda18** [comment]
The thing is I can't enable these shaders. As soon as I enable them, the game hangs and I have to kill the Java process that keeps the game open. Which eventually crashes the game.

**Comment by ProNoob135** [comment]
Haven't had an issue with the game crashing, what version of Iris are you using

**Comment by Polda18** [comment]
As I said, I use Iris 1.5.2, for MC 1.19.4 of course. I can send in full list of mods I am using, including Sodium if you like, but once I get back home from work. I obviously lack access to my home computer from work.

**Comment by scubamount** [comment]
> 

Have you resolved this issue? Iris is now 1.6.3

**Comment by Polda18** [comment]
Not yet, I couldn't update just yet as I had my computer repaired, so I didn't have access to my games. I got it back, but didn't have time to play yet, I just launched the game making sure I still have all my files intact, then I did more important things. I'll update Iris and look into it again once I have all my important stuff sorted out.

**Comment by gri573** [comment]
this issue is basically tech support dragging on for months, so I'll close it
