### ISSUE TITLE
Banners Glitch Out

### ISSUE THREAD

**Issue by Awsome-Creeper9** [gri573/rethinking-voxels#126]
Banners have been glitchy inside of the Rethinking Voxels Shaders. 
![RethinkingVoxelsBanners](https://user-images.githubusercontent.com/62125559/231034615-8075bfe6-141a-430a-8894-a17461fe284b.png)

Edit: Upon further checking, it is Iris' fault, it looks like this in other shaders too, I thought it was Rethinking Voxels because that is the shaderpack I use, and I noticed that disabling shaders made everything look fine.

**Comment by zndrmn** [comment]
are you using iris 1.6?

**Comment by Awsome-Creeper9** [comment]
@zndrmn Good to know, I am in fact using Iris 1.6 as it is the latest version, thanks for informing me.
