### ISSUE TITLE
bad sun shadow filtering

### ISSUE THREAD

**Issue by Pawe98** [gri573/rethinking-voxels#13]
When enabling sun shadows, and not using per pixel shadow option, shadows are really blocky and produce unstable results when hitting a tilted surface. 
Is it possible to fix this, or maybe provide a per pixel option with a resolution slider ?

https://ibb.co/sRdzn34

**Comment by gri573** [comment]
It can be made better (it's slightly better in the latest commit), but a per pixel option with a resolution slider is not possible

**Comment by gri573** [comment]
This is much improved fixed since a few commits
