### ISSUE TITLE
Folaige Shadows are glitchy

### ISSUE THREAD

**Issue by Kogiz** [gri573/rethinking-voxels#130]
You can see it when I walk, they glitch around and are very distracting when running around. They also slightly shimmer which I hate. I love the rest of the shader so much, it's my favorite, but this is turning me away. Any way to fix this and not kill performance?
https://medal.tv/games/minecraft/clips/14ovVZsjxzna2P/d13374cup8L8?invite=cr-MSxCQkMsMjY0MTM1Miw

**Comment by Kogiz** [comment]
Another view
https://medal.tv/games/minecraft/clips/14oz95k2CuzS1I/d1337PEFVv7D?invite=cr-MSxMS0ssMjY0MTM1Miw

**Comment by gri573** [comment]
shadow rendering is back to how it is in complementary reimagined, so it should be fixed now
