### ISSUE TITLE
is there a way to get the lava to glow like it does in complementary reimagined

### ISSUE THREAD

**Issue by Nooooooah818** [gri573/rethinking-voxels#132]
here's 2 screenshots, the lava in complementary is brighter than the other shader, sometimes in complementary the lava is even brighter
![2023-04-15_15 48 20](https://user-images.githubusercontent.com/110315732/232250548-42461bad-7f68-41f0-8c93-07795b000772.png)
and uh yea my laptop doesn't like shaders too well but i use them for screenshots
![2023-04-15_15 47 13](https://user-images.githubusercontent.com/110315732/232250553-1224b20c-1f26-4b49-8c12-5619694f77b0.png)

**Comment by Nooooooah818** [comment]
here's an instance of it being a lot brighter
![2023-04-09_00.53.12.png](https://user-images.githubusercontent.com/110315732/232250948-41241be6-1e41-4a5b-b477-f119086c7d77.png)

**Comment by gri573** [comment]
the complementary reimagined screenshots look quite broken to me, lava looks alright on my end
