### ISSUE TITLE
Minecraft light block support

### ISSUE THREAD

**Issue by Paco-Rubio** [gri573/rethinking-voxels#133]
How can we add minecraft light block support to the shader while waiting until the next update?
Or, how long will it be until next update?

**Comment by Paco-Rubio** [comment]
Where exactly do I need to add those?

Sorry for the inconvenience

**Comment by gri573** [comment]
voxelizeLightBlocks=true goes in [here](https://github.com/gri573/rethinking-voxels/blob/main/shaders/shaders.properties)
for light block support, please follow #35

**Comment by gri573** [comment]
implemented for the next release, it turned out to be an extra line in addition to that

**Comment by Paco-Rubio** [comment]
So I thought, thanks a lot.
