### ISSUE TITLE
pixels all over my screen

### ISSUE THREAD

**Issue by RichPrune** [gri573/rethinking-voxels#134]
self explanatory, just multicolored pixels on the bottom left of my screen slowly moving right, possibly to do with first person animation mod
![2023-04-16_21 33 26](https://user-images.githubusercontent.com/103792572/232357744-d78d6364-e239-4659-a74c-d67ec19603ad.png)

heres latest log
[latest.log](https://github.com/gri573/rethinking-voxels/files/11245389/latest.log)

**Comment by gri573** [comment]
do you happen to have create?

**Comment by gri573** [comment]
yes, you do according to your log. rethinking voxels is incompatible with flywheel, which will cause such artefacts in the form of a "top-down view" of create blocks and some other things (like chests in your case)

**Comment by D3SL** [comment]
That's unfortunate, is this inherent to Rethinking Voxels or is the issue on flywheel or oculus' side?

**Comment by gri573** [comment]
it is an oculus issue that interacts badly with flywheel as far as I know. it will most be fixed once oculus can run the latest version
