### ISSUE TITLE
Strange flickering in certain locations

### ISSUE THREAD

**Issue by ParodyVerse** [gri573/rethinking-voxels#136]
As stated above.
[https://drive.google.com/file/d/1RIwT07_5EqpIjb-DFiwXtvIK2P8kr-Cw/view?usp=sharing](https://drive.google.com/file/d/1RIwT07_5EqpIjb-DFiwXtvIK2P8kr-Cw/view?usp=sharing)

**Comment by gri573** [comment]
most likely fixed in the latest release
