### ISSUE TITLE
Distortion

### ISSUE THREAD

**Issue by GALAGOLD** [gri573/rethinking-voxels#137]
I found that creepers distort shadows 
![2023-04-18_13 43 19-min](https://user-images.githubusercontent.com/123942063/232726069-762db9c6-457e-4c7f-a2f3-00617c41918c.png)
![2023-04-18_13 43 52-min](https://user-images.githubusercontent.com/123942063/232726076-4cfe65f0-5607-42e0-bb25-37bf689410a6.png)

**Comment by DarianLStephens** [comment]
Creepers? What?
What's wrong with the shadows, and where are the creepers?

**Comment by GALAGOLD** [comment]
Sorry, maybe I made a mistake, I don't know much English

**Comment by DarianLStephens** [comment]
Oh, or is this a translation thing, and you're talking about Vines?
That's just how screens-space reflection works. Anything not directly on-screen can't be reflected, so the vines appear to 'cut' the reflection.

**Comment by GALAGOLD** [comment]
Reflections distort from the vines

**Comment by GALAGOLD** [comment]
But it doesn't happen with other shaders.

**Comment by DarianLStephens** [comment]
What 'other shaders'? If they use screen-space reflection, then all they could have are some clever tricks to minimize it.

**Comment by GALAGOLD** [comment]
So is it possible to minimize this?
