### ISSUE TITLE
Beacon Core not showing with Improved Glass Enabled

### ISSUE THREAD

**Issue by SakuraSedaia** [gri573/rethinking-voxels#138]
Hello, I recently downloaded the pack and am currently using it on Minecraft 1.18.2 with Iris 1.6.0. I was messing around with the settings to see how the pack runs on my PC and noticed that when I have Improved Glass Enabled, the Beacon Core dissapears.

Improved Glass [OFF]
![image](https://user-images.githubusercontent.com/61118816/233153483-fac5fdd6-824d-436a-bda4-a4a26a1b3c02.png)

Improved Glass [ON]
![image](https://user-images.githubusercontent.com/61118816/233153650-cc730b87-f81e-43b7-bb2b-49cbe945ec80.png)

**Mod List**:
Architectury API 4.11.90
Cloth Config API 6.4.90
Fabric API 0.76.0
Indium 1.0.7
Iris Shaders 1.6.0
Journey Map 5.9.5
Lithium 0.10.3
Mod Menu 3.2.5
Mouse Tweaks 2.22
Reese's Sodium Options 1.5.0 Build 70
Roughly Enough Items 8.3.594
Skin Layers 3D 1.5.2
Sodium 0.4.1 Build 15
Sodium Extra 0.4.18 Build 98

**PC Build List**:
CPU: AMD Ryzen 9 5900X
RAM: 32gb
Graphics Card: Nvidia 3090 TI 24gb

**Comment by gri573** [comment]
this is a problem with sodium's transparency sorting, not rethinking voxels.
