### ISSUE TITLE
Shadows smoke gas station weed on 1.19.3 (Iris)

### ISSUE THREAD

**Issue by dopadream** [gri573/rethinking-voxels#14]
![image](https://user-images.githubusercontent.com/68942129/210021940-bff56a80-84e2-4040-8158-df4f5385fd92.png)

I have no other mods installed. I'm on the default settings, but the only thing that seems to really fix the issue is enabling pixel perfect shadows, killing performance in the process.

**Comment by arceuss** [comment]
happens for me on 1.19.2 aswell

**Comment by gri573** [comment]
you can only get a limited shadow resolution per performance. increase voxel volume height/size to make it better, but that will also kill performance eventually. this is not fixable (to be more precise, it is working as intended)

**Comment by dopadream** [comment]
bro reopen this right now my voxel volume height was on extreme

**Comment by gri573** [comment]
you can also update to the latest commit, that has fewer hard edges in that situation. if you absolutely can't stand these shadows, you can enable pixel perfect blocklight shadows.
