### ISSUE TITLE
Shadows flicker millions of blocks away from world origin

### ISSUE THREAD

**Issue by SkyTheNerd** [gri573/rethinking-voxels#140]
Shadows flicker millions of blocks away from the world's origin.
The coordinates around where it starts are 8388608 ~ 8388608.
I am using Fabric 1.19.2 with Iris 1.6.1.
[Video](https://cdn.discordapp.com/attachments/867367450022379520/1098944370599800862/2023-04-21_08-06-32.mp4
)

**Comment by gri573** [comment]
that's either an iris problem or something I can't fix
