### ISSUE TITLE
Snowy World goes through glass for some reason? (enhancement)

### ISSUE THREAD

**Issue by Mintyylol** [gri573/rethinking-voxels#141]
Hello! I use the Snowy World setting, and honestly it's very impressive! I have no idea how you've made it.
One small thing, Snow goes through glass ceilings for some reason? I don't know why, it's pretty unrealistic.
Not sure if it's like this with Optifine, as I use Iris for shaders.

[Image Example 1](https://cdn.discordapp.com/attachments/854846463166644255/1098976976104063066/2023-04-21_07.20.41.png)
[Image Example 2](https://cdn.discordapp.com/attachments/854846463166644255/1098978377467175002/image.png)
_the completed/reopened thing is just me not knowing how to use github, lol_

**Comment by zndrmn** [comment]
This is a reimagined issue but I'm pretty sure the reason why it's like that is because the glass is transparent and the shader can't tell the difference between the glass and the sky

**Comment by gri573** [comment]
I could probably fix it because I have voxel data available, but it is not worth it unless I do other things that need the same data as this
