### ISSUE TITLE
Where is the tall grass shadow computed?

### ISSUE THREAD

**Issue by Varunda** [gri573/rethinking-voxels#143]
Hello! 

I am looking to get this shader working with a resource pack I have, one problem I am running into is the shadows for tall grass (not the block) assume the tall grass model is an x shape, while the resource pack uses a custom triangle model. This creates a disjoint shadow that does not match the custom model.

Would you be able to point me to where the shadow for the tall grass is? Thank you!

**Comment by gri573** [comment]
this is fixed with accurate RT, which takes every piece of geometry into account

**Comment by gri573** [comment]
(grass shapes are hardcoded in the raytracer when doing voxel ray tracing, it can't easily be modified unless you would like it to be a full block or a cuboid)
