### ISSUE TITLE
performance / pause

### ISSUE THREAD

**Issue by SJK9906** [gri573/rethinking-voxels#145]
after pausing and resuming minecraft the framerates decries permanently with iris shader 1.6.1 minecraft 1.19.4
as the video at this ink:
https://user-images.githubusercontent.com/129201282/235324018-e328c1c5-fe9c-4e79-8755-2e73015d2120.mp4

#142

**Comment by SJK9906** [comment]
see:
#147

**Comment by gri573** [comment]
this is not an issue with rethinking voxels, but rather with iris having a memory leak in that specific version (as far as I'm aware). shaders have no way of telling if you are in the pause menu or not
