### ISSUE TITLE
Lava looks like a bomb just went off: issue with Anisotropic Filtering and lighting lava

### ISSUE THREAD

**Issue by GlitchTime** [gri573/rethinking-voxels#146]
_Essentially, this issue happens whenever Anisotropic Filtering is above normal levels (Zero is normal btw: Ex. >0)._
The title and pretext really says it all. I will mention I'm using a wide variety of mods with the shader and am running opti-fabric for optifine as it's a fabric instance. Photos attached of mod folder and well... the issue. (Yes it's beta-18d).
![issue2](https://user-images.githubusercontent.com/101536350/235332265-0c1947fa-b5da-4d14-9e3d-535686118110.GIF)
![image](https://user-images.githubusercontent.com/101536350/235332276-55a5ee0c-1f60-4575-98da-d4dce97ee2af.png)
![image](https://user-images.githubusercontent.com/101536350/235332309-b1d9824c-ebee-49a2-a7bd-d48be2ae2782.png)
Edit: Anisotropic Filtering at 0:
![image](https://user-images.githubusercontent.com/101536350/235332579-80321986-c744-428c-9495-43f1c6e796ae.png)

**Comment by SJK9906** [comment]
try to disable mods and turn on gingle mods to find issues mod source

**Comment by zndrmn** [comment]
Anisotropic Filtering breaks when it's changed from its default state, this also happens in reimagined

Most OptiFine settings (in the shader menu) will break reimagined if they are changed, so just don't change them

**Comment by Bipbip2109** [comment]
Why the fuck do you have a .zip in your mod folder

**Comment by GlitchTime** [comment]
> Why the fuck do you have a .zip in your mod folder

No fucking clue why it works it really shouldn't it shows mod health

**Comment by GlitchTime** [comment]
> Anisotropic Filtering breaks when it's changed from its default state, this also happens in reimagined
> 
> Most OptiFine settings (in the shader menu) will break reimagined if they are changed, so just don't change them

That's what I assumed

**Comment by GlitchTime** [comment]
Alrighty then if there's no issue here I'm gonna close the thread.
