### ISSUE TITLE
Advanced lighting gives artifacts with blocks like glass and shadow artifacts

### ISSUE THREAD

**Issue by mshailz** [gri573/rethinking-voxels#149]
When advanced or (medium settings) is turned on, blocks become weird with lighting when glass is placed on the light source. Look at images for a better idea. I was testing this with my own mod and I tried it with low settings and there aren't any issues as far as my mod is concerned. Shadows are also kind of wonky with advanced lighting. I also tested this issue with an offical minecraft light source block, like sea lanterns and the same problem arises. 

**LOW SETTINGS** no issues.

![2023-05-04_12 48 36](https://user-images.githubusercontent.com/89714565/236271826-e4c25162-b2fa-4649-965e-da76998ab32d.png)
![2023-05-04_12 48 31](https://user-images.githubusercontent.com/89714565/236271828-ce268aa2-a931-412e-b227-db558eb42f7e.png)

**MEDIUM SETTINGS** light and shadow artifacts.
![2023-05-04_12 47 40](https://user-images.githubusercontent.com/89714565/236271967-c9219ac8-b11d-4e38-83de-3bdbabd6f0aa.png)
![2023-05-04_12 19 06](https://user-images.githubusercontent.com/89714565/236271969-dee96c5e-a3c0-44f5-9e48-45aba9d5e85d.png)
![2023-05-04_12 19 16](https://user-images.githubusercontent.com/89714565/236271970-98c827dc-26c2-411f-ae61-49027841ee5c.png)
![2023-05-04_12 20 33](https://user-images.githubusercontent.com/89714565/236271972-3810ec11-1d64-45a2-a563-2fd8d2e2f72a.png)

**Comment by gri573** [comment]
this should be fixed in the latest version
