### ISSUE TITLE
[SUGGESTION] Create mod compat

### ISSUE THREAD

**Issue by KaziiTheAvali** [gri573/rethinking-voxels#150]
i wanna suggest create mod  shaddows to some of the blocks and such if possible. aswell as some of the lights. such as create:blaze_burner
create:rose_quartz_lamp
![image](https://user-images.githubusercontent.com/87594664/236361846-e38900ad-afd7-416a-aa34-402cb5426aea.png)

**Comment by Niron68** [comment]
I suggest to make a toggable option if shadow on create mod is added. Otherwise would be unplayable near big farm

**Comment by KaziiTheAvali** [comment]
that sounds like a great idea.

**Comment by gri573** [comment]
all modded things have sun shadows (and, with accurate RT, also shadows from block light) in the latest version
