### ISSUE TITLE
TerraFirmaCraft water conflict

### ISSUE THREAD

**Issue by Hranitel** [gri573/rethinking-voxels#152]
playing with the TerraFirmaCraft mod and your shader, the water in the ocean is broken
![2023-05-07_14 26 04](https://user-images.githubusercontent.com/12985354/236663921-3223a458-5e73-46ef-875d-026abd799540.png)

**Comment by gri573** [comment]
this should be better with the latest version, i.e. the shadow should be gone, but it will still not be shaded like water. that's as good as it will become probably
