### ISSUE TITLE
Light shines through mountains (distant objects not making shadows).

### ISSUE THREAD

**Issue by dragon3025** [gri573/rethinking-voxels#155]
I'm using Beta 18d for 1.19.4. Something I noticed is light is shinning through mountains. In the picture below I have it set to Ultra settings. There is still shadows coming from trees, but it seems like distant objects aren't blocking the sun.
![PK2pt5M](https://github.com/gri573/rethinking-voxels/assets/11652210/1e8147c1-7a13-4071-b503-10dced690b36)

**Comment by Mhanz3500** [comment]
I wrote something in your reddit post, but I'm not sure of what I said, please gri573 make some documentation.
the reddit post: https://www.reddit.com/r/minecraftshaders/comments/13etzla/light_shines_through_mountains_distant_objects/

**Comment by dragon3025** [comment]
I can see now that it's tied to the volume height and shadow res settings, but even with it turned all the way up, only the bottom half of the mountain blocks the sun. Would a separate option for shadow resolution fix this?

**Comment by gri573** [comment]
it is fixed on the latest version

**Comment by dragon3025** [comment]
It's a lot better. I'm fine with using a render distance of 12 with it, but it still peeks through if anyone uses over 12. A chunk distance slider for it could help. Here's an example picture:
![2023-06-10_12 43 09](https://github.com/gri573/rethinking-voxels/assets/11652210/2cf799ed-a225-470e-a3cc-7b2c6d540469)
