### ISSUE TITLE
Vsync caps FPS to half of monitor refresh rate

### ISSUE THREAD

**Issue by Delivator** [gri573/rethinking-voxels#156]
With other shaders enabling vsync works as expected and the game caps my FPS to my monitors refresh rate at 144 FPS/HZ.
With this shader it is caped at 72 FPS. Is there a setting I am missing to change that?

**Comment by zndrmn** [comment]
Minecraft's Vsync is broken so don't expect it to work how you think it should

**Comment by Delivator** [comment]
Okay didn't know that. I guess I can close this then?

**Comment by awesomepowner** [comment]
That's just how Vsync works. It caps your framerate to half of your refresh rate (so 72fps on 144hz) if it isn't reaching the full refresh rate. Your next best option is to set the framerate lock to 140fps so it doesn't bring in screen tearing (assuming that's why you have Vsync on).
