### ISSUE TITLE
Incompatibility with Ocean Physics from Physics Mod Pro

### ISSUE THREAD

**Issue by cec1Ie** [gri573/rethinking-voxels#159]
As the title states. Other shaders like complimentary reimagined work fine with this setting

**Comment by Kyle-Sang** [comment]
Same problem, worked fine with an optifine-forge setup on 1.19.4. However, when switching to Fabric, Iris-Sodium, it no longer works with ocean physics.

**Comment by samjviana** [comment]
Just wanted to add that the particles generated by the Physics Mod Pro end up triggering shadow bugs on light sources that are not the sun. The sunlight interacts well with these particles.

**Comment by gitguette** [comment]
same issue

**Comment by gri573** [comment]
see #216
