### ISSUE TITLE
shulker boxes and beds shadows flickering (both in sunlight and block light)

### ISSUE THREAD

**Issue by power2220** [gri573/rethinking-voxels#16]
https://user-images.githubusercontent.com/87595312/210367972-2922662c-991a-428f-904d-aa24271d5012.mp4

**Comment by gri573** [comment]
I can reproduce beds, but not shulker boxes flickering. Beds are fixed in the latest commit

**Comment by gri573** [comment]
ok, I am also able to reproduce shulker boxes now, fixed in latest commit
