### ISSUE TITLE
Doodads mod glare light not rendering light

### ISSUE THREAD

**Issue by darknesschaos** [gri573/rethinking-voxels#161]
The Doodads mod has an invisible light source that I cannot get to render light even when setting in the fallback color. I figure the uncommon nature of this block might make it not supported. The flame you see in the picture is the fire flare particle.

![2023-05-29_01 29 50](https://github.com/gri573/rethinking-voxels/assets/573435/de27dc42-4e61-4175-a694-8b5a257dfb53)

**Comment by gri573** [comment]
it is impossible for rethinking voxels to support invisible light sources unless the shader loader adds special handling for them (such as the minecraft light block on iris). this is unlikely to happen.
