### ISSUE TITLE
Giant entity Shadows

### ISSUE THREAD

**Issue by ThePotatoGamer0** [gri573/rethinking-voxels#162]
I'm using Oculus on forge with Windows and almost all entities have giant shadows.

[Video (Google Drive)](https://drive.google.com/file/d/1bSZM5tADD6zsmn3FmJXsJbJ91vzCmCuK/view?usp=share_link)

No clue what's wrong was using complementary reimagined before with entity shadows maybe that's it.

**Comment by LeHoovy** [comment]
Having a similar problem. I never had a problem with the actual entity shadows, but I can still show my similar problem.
(As I was recording the video to show the problem, the same exact problem occurred)
[Video](https://drive.google.com/file/d/14O56Q9uptOUeKKQ6qt1P3LLDXoh-gH6o/view?usp=sharing)

**Comment by JupiterboyLuffy** [comment]
I don't even have entity shadows. What option did you use to even enable them?

**Comment by gri573** [comment]
that will be fixed once oculus can run the latest version of rethinking voxels. you can work around it for now by disabling entity voxelisation and adding the line `shadowBlockEntities=false` to `shaders/shaders.properties`
