### ISSUE TITLE
[BUG] Block light causes player hand to become semi-transparent

### ISSUE THREAD

**Issue by deathbymanatee** [gri573/rethinking-voxels#167]
OS: Arch Linux x86_64 (updated yesterday)
GPU: AMD Radeon 6950 XT
Minecraft version: 1.19.4, Iris + Sodium
Shader version: r0.1-alpha1a

Title. This does not happen with sunlight or any other natural light source; only light emitted by blocks. Happens with lava, too

![2023-06-03_14 28 58](https://github.com/gri573/rethinking-voxels/assets/130176904/6d7b687e-5e2e-44d7-afe8-3f5978d33dff)

Unrelated, but this is a beautiful shader. Keep up the good work!

**Comment by ZachIsCool123321** [comment]
Similar Issue with held items on version 1b, issue isn't very important as I personally do not mind, in some ways its kind of useful.

**Comment by gri573** [comment]
it is fixed in the last few commits

**Comment by BuggyAl** [comment]
Related to this, block light is rendered through the player's hand. (all 3 blocks are light emitters)
![image](https://github.com/gri573/rethinking-voxels/assets/64368488/a8b19f05-5db4-4877-b7b4-51cdc6142f45)
