### ISSUE TITLE
Complimentary Reimagined welcome message still in pack

### ISSUE THREAD

**Issue by CocoaHere** [gri573/rethinking-voxels#17]
Not a major issue, but led me to asking them for help with the project. They appear to not be affiliated.

**Comment by zndrmn** [comment]
Should it be like "Complementary: **Rethinking Voxels**" or "Rethinking **Voxels**"
Hmm I think the first one is better.

I have a PR open so I'll add this to it because why not.
( Bold means that it will change color when you click on it )

**Comment by gri573** [comment]
fixed on latest commit
