### ISSUE TITLE
Held Light Shadows disables rendering in Alpha r0.1 1b

### ISSUE THREAD

**Issue by ZachIsCool123321** [gri573/rethinking-voxels#170]
On Iris 1.6.2, shader fails to render when Held light shadows is enabled. This can be mitigated if Dynamic Hand Held Lighting is set to off; however, this makes the function of Held Light Shadows irrelevant. Tested on latest build of GhostSpectre Win11, Rtx3090 latest drivers, Ryzen 5800x. No log is provided from what I can tell.

**Comment by gri573** [comment]
fixed in alpha 2
