### ISSUE TITLE
Nether 

### ISSUE THREAD

**Issue by Sagevidz** [gri573/rethinking-voxels#171]
When walking around the nether lights seem to pick and choose where they render at random im just walking back and forth 

![Screenshot (14)](https://github.com/gri573/rethinking-voxels/assets/135848443/6baa7c00-6627-43e3-845c-d9c8b1589a79)
![Screenshot (9)](https://github.com/gri573/rethinking-voxels/assets/135848443/86d63796-ae2b-496e-9d2e-32036cb14944)
![Screenshot (10)](https://github.com/gri573/rethinking-voxels/assets/135848443/f7348d17-6a15-49d9-ac02-e0a11b1fc676)
![Screenshot (8)](https://github.com/gri573/rethinking-voxels/assets/135848443/06e36df4-03ab-45c2-8bde-129a35596502)
![Screenshot (11)](https://github.com/gri573/rethinking-voxels/assets/135848443/dcf1d15b-57df-45c3-bbb3-2164e95d6390)
![Screenshot (12)](https://github.com/gri573/rethinking-voxels/assets/135848443/35b458db-3ea2-4352-b5f0-0029b4b9be3f)
![Screenshot (13)](https://github.com/gri573/rethinking-voxels/assets/135848443/ae760b20-73f1-4de3-8d7e-8c400ab7bfa9)

**Comment by gri573** [comment]
this is now "fixed", at the cost of #181 / #182
