### ISSUE TITLE
No light emitting from blocks in Fabric Version

### ISSUE THREAD

**Issue by Fox-GAMING** [gri573/rethinking-voxels#173]
I'm having a strange bug. I just installed Rethinking Voxels, and I cannot seem to get any light source to work. I am completely in the dark. Handheld light sources work, but as soon as I place them down, nothing.
![2023-06-08_17 06 02](https://github.com/gri573/rethinking-voxels/assets/74867607/cd48e774-848f-4aa3-8be1-18590fa58a1b)

Minecraft 1.18.2
Fabric API 0.76.0
Iris 1.6.0
Sodium 0.4.1 Build 15
Optifine 1.18.2 HD U H6

![2023-06-08_17 13 26](https://github.com/gri573/rethinking-voxels/assets/74867607/5f58ab0d-db3a-4175-8070-f686d01476e0)

**Comment by Fox-GAMING** [comment]
So I found that rather than loading with Fabric, but Iris + Sodium, it works:
![2023-06-08_17 26 55](https://github.com/gri573/rethinking-voxels/assets/74867607/abe51508-b4e1-40b0-b15a-95cd17cf6450)
However, it has this incredible grain over everything, and my held items are slightly transparent.

**Comment by Fox-GAMING** [comment]
![2023-06-08_17 29 39](https://github.com/gri573/rethinking-voxels/assets/74867607/81b70070-647b-445f-bd39-44cd038a04a6)

**Comment by Fox-GAMING** [comment]
Also, I had the physics mod fabric version loaded when I used the Fabric game version. Banners were also messed up then. I had to turn them off in dynamic blocks, they looked mostly transparent. However even with them off, some layers of colors in the banners would not show through.

**Comment by FreeRigz** [comment]
Hey, i would like to know how you semi-fixed the list, AKA there was lots of grain. I have a hard time understanding 'So I found that rather than loading with Fabric, but Iris + Sodium, it works' how did you load iris and sodium without fabric? I would really liek to know how you fixed it since im stuck here with the same lightless issue. Thanks

**Comment by FreeRigz** [comment]
> Hey, i would like to know how you semi-fixed the list, AKA there was lots of grain. I have a hard time understanding 'So I found that rather than loading with Fabric, but Iris + Sodium, it works' how did you load iris and sodium without fabric? I would really liek to know how you fixed it since im stuck here with the same lightless issue. Thanks

Never mind, i found a solution. I was using an older version of iris and sodium, i updated it to the latest and everything was fine. Didn't get any grain though so try that out, incase you did not yet.
