### ISSUE TITLE
[???] Debug/status bar at bottom of screen

### ISSUE THREAD

**Issue by deathbymanatee** [gri573/rethinking-voxels#174]
Not sure if I just didn't dig deep enough in the menu for the setting that turns it off, but there is a status bar at the bottom of the screen that flashes green and red occasionally 

![2023-06-08_16 30 13](https://github.com/gri573/rethinking-voxels/assets/130176904/b90ee3fb-4e8e-4bca-9de1-4bc1f2877bd5)

Labeled as [???] because it may just be a skill issue on my end

**Comment by DarianLStephens** [comment]
They mentioned on Discord that it was a debug bar they forgot to turn off prior to release.

**Comment by deathbymanatee** [comment]
well if it was mentioned by the dev(s?) then i guess no point in keeping it open
