### ISSUE TITLE
these light line things. change with light emitters 

### ISSUE THREAD

**Issue by KaziiTheAvali** [gri573/rethinking-voxels#175]
![image](https://github.com/gri573/rethinking-voxels/assets/87594664/7c9dad06-ba07-423b-84f4-2524056ca36c)
i am unshure what these are. they seem to be relating to light levels. maby debug info
i am on linux (OS: Garuda Linux x86_64) 
my gpu is AMD Radeon RX 5700
my cpu is AMD Ryzen 7 2700X (16) @ 3.7 GHz
this does not hinder my enjoyment of the shader but is a bug none the less

**Comment by KaziiTheAvali** [comment]
![image](https://github.com/gri573/rethinking-voxels/assets/87594664/d21271a8-d77e-4c58-b5be-b438df59e721)
update they become less and less. my hand is also invisable/semitransparent

**Comment by BuggyAl** [comment]
Appears to be similar to #167, the block light emitted renders through the player hand.
![image](https://github.com/gri573/rethinking-voxels/assets/64368488/1157f481-3640-473e-be93-89f97b17fbca)

**Comment by deathbymanatee** [comment]
in regards to the bar, it is a debug thing that wasn't turned off before release

**Comment by KaziiTheAvali** [comment]
> Appears to be similar to #167, the block light emitted renders through the player hand. ![image](https://user-images.githubusercontent.com/64368488/244729862-1157f481-3640-473e-be93-89f97b17fbca.png) ngl i didnt even notice the hand thing untill i noticed how much it was moving

**Comment by KaziiTheAvali** [comment]
> in regards to the bar, it is a debug thing that wasn't turned off before release

ok. that is good. i thought it was a bug with my gpu.

**Comment by SJK9906** [comment]
i have the bug
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/06c53453-93a1-4648-a0d1-11d6a939f935">

> ![image](https://user-images.githubusercontent.com/87594664/244577796-d21271a8-d77e-4c58-b5be-b438df59e721.png) update they become less and less with more light emitters. my hand is also invisable/semitransparent
