### ISSUE TITLE
underwater light distortion

### ISSUE THREAD

**Issue by SJK9906** [gri573/rethinking-voxels#176]
if you use iris shaders when you are under water there are an error with the light

rethinking-voxels beta18e.zip
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/ac3410d9-c55b-469f-9543-e2f8a65229ee">
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/1a1b2673-0e60-4b63-922d-d1655409a82a">

rethinking-voxel r0.1alpha1a.zip
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/eb5a0cd6-1f36-4d45-a300-349bda6c3d8c">
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/fdaed17b-eaaf-406c-b9d4-ac5cd231a0e2">

the problem there are in the Optifine version
<img width="959" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/05381d2f-6cc1-4519-a9aa-b67541834d63"> (rethinking-voxels beta18e.zip)

**the test are made with rethinking-voxel r0.1alpha1a.zip**
test before reloading shader
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/ce74d029-0df3-4779-a497-8f6605f3b062">

test after reloading shader
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/5f875028-740a-429f-a37f-283a8fe70782">

test after interacting with the game after reloading shader
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/d90f6671-62b3-4bf6-b6cc-63988e20701b">

test above the water (player and light sours)
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/de8733e4-13d1-4094-8b16-5ab98eb7053a">

test above the water (player only)
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/2c64e4a4-6707-42e7-8c71-94ab73a31a4c">

the issues probably caused by a water sours on the light sours

**Comment by gri573** [comment]
see #248  , that's the same issue, where I will track this from now on
