### ISSUE TITLE
farther light sours problem

### ISSUE THREAD

**Issue by SJK9906** [gri573/rethinking-voxels#177]
farther light sours aren't rendered in rethinking.voxel_r0.1_alpha3.zip

near lights
<img width="960" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/c666502d-8b54-410a-9701-aa071fd9bf7f">

far lights
<img width="959" alt="image" src="https://github.com/gri573/rethinking-voxels/assets/129201282/57cb41b5-35bf-4c63-96ae-68c3e1acc7b1">

**Comment by gri573** [comment]
that is intended. rethinking voxels has a limited range in which it calculates lighting due to performance and memory reasons. beyond that, it falls back to the vanilla light map

**Comment by SJK9906** [comment]
but in the beta edition the problen aren't present,
what is the correct versione of the shader which beta and alfa?
