### ISSUE TITLE
[?-1.20] Amethyst blocks do not emiss when placed in the world.

### ISSUE THREAD

**Issue by NocturnalSergal** [gri573/rethinking-voxels#178]
While having the settings in the shaderpack set to allow emissive amethyst crystals and blocks, the blocks do not seem to emiss regardless of the setting, the item in hand does but does not in the world.

https://i.imgur.com/q4cw5LX.jpeg
https://i.imgur.com/dwcqmGg.jpeg
https://i.imgur.com/9lAZAQw.jpeg

Unsure if this is intended or a bug, adding the blocks to the modded emissions block1234 only produces a faint white tinted light instead of the strong emission from hand

**Comment by NocturnalSergal** [comment]
screenshot of F3 menu JIC: https://i.imgur.com/PkGbaI0.jpeg

**Comment by Guiyom01** [comment]
Is the setting on in the shader menu ? I've seen that there is an option for cristals only and block and cristal

**Comment by NocturnalSergal** [comment]
> Is the setting on in the shader menu ? I've seen that there is an option for cristals only and block and cristal

3rd image link shows the shader settings page where it’s set to “Crystal and Block”

**Comment by gri573** [comment]
that's intended, only amethyst clusters / amethyst buds emit blocklight. glowing is a different effect, which only means that the shader will treat the surface of the amethyst block as bright regardless of the amount of light falling on it
