### ISSUE TITLE
Lights flicker in r0.1_alpha4

### ISSUE THREAD

**Issue by Mintyylol** [gri573/rethinking-voxels#179]
I created a test house in an empty world, to test lighting issues I'd gotten in my survival world.

_I tested with and without my VanillaTweaks resource pack (I'm using various 3d model tweaks, like on trapdoors), and had the same issues both with and without._

 

https://github.com/gri573/rethinking-voxels/assets/109185054/3a843671-a136-4595-af46-7b11d95c603a
- First example shows a Campfire intensely casting lights on a wall, that flickers sometimes. 
- Second example shows Redstone Lamps causing a lot of random lights around the room. 
_Through more testing, being behind trapdoors doesn't matter, and does the same effect when just out in the open. Torches also have a similar, but lesser issue like this._
- Third example just shows the issue with torches mentioned previously.

 

I also tested all of these on beta18d, and none of these issues were apparent. beta18d works, and looks  great on my system.

Specs you probably don't need:
My Settings (worked fine on previous versions): https://pastebin.com/QXpcXNaw
Iris v1.6.4
Minecraft 1.20
1650 Super

**Comment by ghosty141** [comment]
I noticed the most flickering on stairs, and I cant really fix it with settings.

**Comment by SJK9906** [comment]
i have this isuess if i set "per block" in alpha4a, alpha3a

**Comment by Rebel459** [comment]
I have this issue with all light sources with any settings combination (that I could find). Tested in 1.20 and 1.20.1

**Comment by RoyalQX** [comment]
accurate raytracing fixes it for me but isnt very playable because of the drop in performance

**Comment by gri573** [comment]
fixed in alpha 5 or later
