### ISSUE TITLE
 Conduits emit no light

### ISSUE THREAD

**Issue by Lolothepro** [gri573/rethinking-voxels#180]
## Describe the bug:
Conduits emit no light

## Screenshot:

![2023-06-12_22 01 25](https://github.com/gri573/rethinking-voxels/assets/68275908/dc9e59e5-eb7d-40c5-809c-73075e7900ed)

## Environment :
Optifine Version: 1.20_HD_U_I5_pre3
Minecraft Version: 1.20.1
Shaderpack Version: r01-alpha4
Graphics Card and Driver Version: NVIDIA 535.43.02 | GTX 1070
Operating System: Ubuntu 22.04
CPU: Ryzen 5 1600
Amount of System Memory (total and assigned to Java): 4Go/16Go

**Comment by gri573** [comment]
there is no version 2.0 of rethinking voxels. which version did you use? (and f3 debug screenshot would answer this too)

**Comment by Lolothepro** [comment]
> there is no version 2.0 of rethinking voxels. which version did you use? (and f3 debug screenshot would answer this too)

r01-alpha4

**Comment by gri573** [comment]
hopefully, this is fixed with alpha 5
