### ISSUE TITLE
Big performance problem with -- Better Nether Mod -- ( r01-alpha4 )

### ISSUE THREAD

**Issue by barylapl** [gri573/rethinking-voxels#181]
With 01 alpha4 ver. (2nd image) performance hit is minor in overworld. When I went to nether my fps as you can see are at excatly 12 while on ver. beta18d (1st image) are at ~65
+ large portion of the chunks in alpha4 are not lit up at all as it seems they "forgot to load up lights" xd ( in image 2 im pointing at it )

hope it helps 

![2023-06-14_01 25 40](https://github.com/gri573/rethinking-voxels/assets/93883690/b8928396-7d43-49b1-875f-1eb2c6e1fefd)
![2023-06-14_01 27 33](https://github.com/gri573/rethinking-voxels/assets/93883690/10ea9083-49de-4580-9f42-455406ad8a29)

**Comment by barylapl** [comment]
r01-alpha4
![2023-06-14_01 42 52](https://github.com/gri573/rethinking-voxels/assets/93883690/07452de6-af89-43a8-b141-602fce422da1)

**Comment by gri573** [comment]
the new pipeline scales badly with the amount of lights, hence the low performance in the nether on the alpha versions. a fix would mean another rewrite, and I have an idea for a solution, which you can expect to see in another few months

**Comment by gri573** [comment]
fixed with alpha 5, which is said rewrite
