### ISSUE TITLE
Shader in Nether Bellow y63 is lagging

### ISSUE THREAD

**Issue by Darkerowl** [gri573/rethinking-voxels#182]
The shader below Y63 in the Nether has been sending my video card to 100% and it will lag the game and my PC out until I get back above Y62. I have tried to run the shader without mods except what I need to run the shader and still same issue I have also changed all the settings to off or low as they can go and still have the same issue. I have noticed when I jump to the lag point I can see light and lava through solid blocks and when it lags the lighting will change some also. Do you have any suggestions on what may help fix or band-aid this issue?

**Comment by gri573** [comment]
I recently added the pipeline to the nether without considering that it would be completely overwhelmed by the sheer amount of lights. you can remove all files matching `shaders/world-1/shadowcomp*` to disable the pipeline in the nether, however, that will mean that there will be no lights in the voxelisation range. however, it will probably be more playable

**Comment by Darkerowl** [comment]
Thank you! Also since a rewrite will take a while to get the Nether up to full Fps is deleting those files the only way? or is there a setting change (ingame) or code that I can input that will allow it to work or bringing over old files from V3? If not that's okay just thought I would ask because I love the shadder it's one of the best in my opinion! 


Also may I ask, why does the pipeline only mess with my video card and lag bellow Y63 I have been thinking about that tons and it's a total mystery to me and very interesting also but I have no idea why? do you? If so would you be able to break it down if not to much trouble I'm a novice just getting into mod code and I am very intrigued.

**Comment by EmberFenn** [comment]
I've also noticed that below a certain Y level in the overworld, the performance seems to take a hit as well, just not as hard as in the Nether. This doesn't happen in previous versions.

**Comment by Guiyom01** [comment]
I've noticed that the problems seems to come from lava, large chunks of lava greatly reduces the framerate even in the overworld, the Y of the lava surface in the nether is 30-31, the problem might come from the fact that lightning doesn't seems to load when youre more than 30 blocks away from the light source

**Comment by gri573** [comment]
fixed in alpha 5 and later
