### ISSUE TITLE
Incompatibility with macOS -- ( r01-alpha4 )

### ISSUE THREAD

**Issue by TobynP** [gri573/rethinking-voxels#184]
On a macOS device, upon toggling the shader an error message appears reading, "Shaderpack Incompatible! The shader pack you are trying to load contains features unsupported by your PC. Please try using another pack. List : Compute shaders, Ssbo, Custom Images. MacOS is known to have issues with many shader packs." 

My device is an M2 MacBook Pro 13" and my primary use for the shader is rendering with Replay Mod.
![RethinkingVoxelsError](https://github.com/gri573/rethinking-voxels/assets/136950800/ab1e098d-d456-46d9-9d8e-bc408495ba06)

**Comment by gri573** [comment]
macOS support was dropped in the alpha versions due to it not supporting modern openGL. there's nothing I can do about it, your best bet is trying to bug apple to improve their openGL drivers

**Comment by cph101** [comment]
Can confirm I have the same error. Very annoying that this has been closed :(
