### ISSUE TITLE
someties everything just starts to turn black rethinking-voxels_r0.1_alpha4

### ISSUE THREAD

**Issue by Cristelknight999** [gri573/rethinking-voxels#189]
Sometime my handitems randomly start filling the screen with  a void. and it is like 3d in the room. never saw something like that. 1 time i got that crash below
[hs_err_pid9552.log](https://github.com/gri573/rethinking-voxels/files/11795968/hs_err_pid9552.log)
![2023-06-19_20 09 54](https://github.com/gri573/rethinking-voxels/assets/54945257/bb3eea84-5c92-4b3e-8fe7-15a5c142dd75)

**Comment by DarianLStephens** [comment]
I've seen the same sort of thing before, just in the Nether while fighting Blazes. After they lit some fires, the all-consuming void appeared.
