### ISSUE TITLE
M1 Mac Performance

### ISSUE THREAD

**Issue by Ghostkwebb** [gri573/rethinking-voxels#19]
Sooooooo I get like 10fps when using the shader. The shaders are amazing and other shaders work great buuuuuut I get like no fps.

**Comment by gri573** [comment]
That's expected. Macs are not meant for gaming in the first place, and minecraft doesn't run natively on M1, so performance is not that great. You can use Iris and ResolutionControl+ and render the game at a lower resolution internally, as well as setting voxel volume size to low in voxelisation settings -> high performance impact

**Comment by Ghostkwebb** [comment]
The thing is recently even though the Minecraft launcher isn't mac native, Minecraft itself which runs on java is apple silicon native which has increased the performance of Minecraft greatly!
So many shaders work flawlessly without any problems on more than 75fps on native mac resolution. That's why I ask about this.
