### ISSUE TITLE
Light dissappears and no light from carpet covered light bocks

### ISSUE THREAD

**Issue by phun-ky** [gri573/rethinking-voxels#191]
When using your shader pack, which is great btw, I am surrounded by shadow, that follows me and darkens areas where there is light, approximately a 64 block square shadow. Is this a setting I need to fix? I am using optifine. Further, there are no lights coming from carpet covered light blocks :( 

![2023-06-20_23 19 57](https://github.com/gri573/rethinking-voxels/assets/1714029/8b755b7d-42d0-4f47-91e3-b0c0a2698863)
![2023-06-20_23 19 59](https://github.com/gri573/rethinking-voxels/assets/1714029/256d2e29-a713-41a7-9193-e35279847bdc)
![2023-06-20_23 14 14](https://github.com/gri573/rethinking-voxels/assets/1714029/2f308356-0fde-4a2e-b30b-edc81531a0fb)
![2023-06-20_23 14 37](https://github.com/gri573/rethinking-voxels/assets/1714029/f34d5949-058b-4bf2-b689-6cad55e0872d)
![2023-06-20_23 14 49](https://github.com/gri573/rethinking-voxels/assets/1714029/ecf3942d-f221-4a80-995a-79f54be7b192)
![2023-06-20_23 14 56](https://github.com/gri573/rethinking-voxels/assets/1714029/c168cb8d-a09f-4fae-a566-d7673f62a427)

**Comment by Drunkraven** [comment]
I have the exact same issue

**Comment by FreeRigz** [comment]
try checking the version of iris and sodium, make sure they are the latest for your minecraft version.

**Comment by dvanw6** [comment]
Same issue here except with moss carpet

**Comment by gri573** [comment]
carpet is opaque, I blame minecraft for letting light pass through it in the first place.

**Comment by dvanw6** [comment]
> carpet is opaque, I blame minecraft for letting light pass through it in the first place.

It's used a lot for hidden lightning though. I use moss carpet to hide torches under the ground outside builds so that the ground is lit up, but no torch spam can be seen

**Comment by gri573** [comment]
that's a good point. I don't want to implement special cases though, at least not before having a version of the shader I am happy with, and, as this is the physically correct behaviour, it would need to be optional. as such, I won't add it for now
