### ISSUE TITLE
Shader Failed to Load (Iris 1.6.4 for 1.20.1

### ISSUE THREAD

**Issue by JackIt999** [gri573/rethinking-voxels#193]
Tried to load shader and I got this message in-game.

"The shaderpack failed to load! Please report the error to the shader developer"

Here is the error log.
`composite8.fsh: composite8.fsh: 0(229) : error C0000: syntax error, unexpected identifier, expecting reserved word or reserved word "in" or reserved word "out" or reserved word "uniform" at token "buffer"
0(231) : error C1503: undefined variable "voxelVolume"
0(248) : error C0000: syntax error, unexpected identifier, expecting reserved word or reserved word "in" or reserved word "out" or reserved word "uniform" at token "buffer"
0(255) : error C0000: syntax error, unexpected identifier, expecting reserved word or reserved word "in" or reserved word "out" or reserved word "uniform" at token "buffer"
0(258) : error C0000: syntax error, unexpected '}' at token "}"
0(259) : error C0000: syntax error, unexpected identifier, expecting reserved word or reserved word "in" or reserved word "out" or reserved word "uniform" at token "buffer"
0(263) : error C0000: syntax error, unexpected '}' at token "}"
0(264) : error C0000: syntax error, unexpected type identifier, expecting '{' at token "iimage3D"
0(265) : error C0000: syntax error, unexpected type identifier, expecting '{' at token "iimage2D"
0(297) : error C7011: implicit cast from "int" to "uint"
0(317) : error C7011: implicit cast from "int" to "uint"
0(317) : error C7011: implicit cast from "int" to "uint"
0(317) : error C7011: implicit cast from "int" to "uint"
0(318) : error C7011: implicit cast from "int" to "uint"
0(319) : error C7011: implicit cast from "int" to "uint"
0(321) : error C7011: implicit cast from "int" to "uint"
0(321) : error C7011: implicit cast from "int" to "uint"
0(322) : error C7011: implicit cast from "int" to "uint"
0(322) : error C7011: implicit cast from "int" to "uint"
0(323) : error C7011: implicit cast from "int" to "uint"
0(323) : error C7011: implicit cast from "int" to "uint"
0(324) : error C7011: implicit cast from "int" to "uint"
0(324) : error C7011: implicit cast from "int" to "uint"
0(325) : error C7011: implicit cast from "int" to "uint"
0(325) : error C7011: implicit cast from "int" to "uint"
0(326) : error C7011: implicit cast from "int" to "uint"
0(326) : error C7011: implicit cast from "int" to "uint"
0(327) : error C7011: implicit cast from "int" to "uint"
0(327) : error C7011: implicit cast from "int" to "uint"
0(328) : error C7011: implicit cast from "int" to "uint"
0(328) : error C7011: implicit cast from "int" to "uint"
0(329) : error C7011: implicit cast from "int" to "uint"
0(333) : error C7011: implicit cast from "int" to "uint"
0(333) : error C7011: implicit cast from "int" to "uint"
0(333) : error C7011: implicit cast from "int" to "uint"
0(334) : error C7011: implicit cast from "int" to "uint"
0(334) : error C7011: implicit cast from "int" to "uint"
0(334) : error C7011: implicit cast from "int" to "uint"
0(341) : error C7011: implicit cast from "int" to "uint"
0(341) : error C7011: implicit cast from "int" to "uint"
0(341) : error C7011: implicit cast from "int" to "uint"
0(356) : error C1009: "texcoord" is not member of struct "vxData"
0(356) : error C1009: "texcoord" is not member of struct "vxData"
0(356) : error C1009: "texcoord" is not member of struct "vxData"
0(396) : error C1115: unable to find compatible overloaded function "readVxMap(ivec2)"
0(397) : error C1102: incompatible type for parameter #1 ("worldPos.49")
0(404) : error C1503: undefined variable "getVxPixelCoords"
0(426) : error C1503: undefined variable "getVxPixelCoords"
0(454) : error C1503: undefined variable "getVxPixelCoords"
0(496) : error C1503: undefined variable "getVxPixelCoords"
0(523) : error C1503: undefined variable "SHADOWRES"
0(523) : error C1503: undefined variable "VXHEIGHT"
0(525) : error C1503: undefined variable "VXHEIGHT"
0(525) : error C1503: undefined variable "VXHEIGHT"
0(525) : error C1503: undefined variable "VXHEIGHT"
0(525) : error C1503: undefined variable "VXHEIGHT"
0(526) : error C1503: undefined variable "getVxPixelCoords"
0(526) : error C1503: undefined variable "vxRange"
`

**Comment by ThePineappleIsNotAvailable** [comment]
The shader also does not load for me when using iris on 1.20 or 1.20.1. Although I didn't check the error.

**Comment by Evander0** [comment]
my oculus 1.6.4 at 1.18.2 seems not working, maybe iris is having the same problem?

**Comment by gri573** [comment]
please try and see if it works with the latest version, which I think it probably does.
