### ISSUE TITLE
Bamboo and cherry blocks don't have correct voxel models.

### ISSUE THREAD

**Issue by InvincibleAoXiang** [gri573/rethinking-voxels#195]
![2023-06-24_12 13 47](https://github.com/gri573/rethinking-voxels/assets/36093236/8de6094c-e953-413b-8a22-6388eef88172)
Bamboo and cherry fences don't cast shadows and their doors have strange shadows.
These fences and doors on the right side are for reference.

![2023-06-24_12 19 13](https://github.com/gri573/rethinking-voxels/assets/36093236/3f628df3-765f-4b8d-86df-1b24923e6725)
Everything works fine when accurate ray tracing is enabled.

**Comment by gri573** [comment]
fixed with alpha 5 and later
