### ISSUE TITLE
Improve User-Friendliness of Shaderpack Download

### ISSUE THREAD

**Issue by CassieCatYT** [gri573/rethinking-voxels#20]
I'm sorry to waste your time but I am too stupid to know how to download this since there are no releases, just a ton of folders.

**Comment by zndrmn** [comment]
The README.md shows you how to download it but,
click on Download ZIP

idk if your able to but you should probably close the issue once you figure it out

![image](https://user-images.githubusercontent.com/77690119/211184355-8453870a-a39d-4aa5-a8ec-fa179b79266b.png)

**Comment by gri573** [comment]
There will soon also be a modrinth page for this shaderpack

**Comment by gri573** [comment]
modrinth page is live
