### ISSUE TITLE
Fog underground acting weird

### ISSUE THREAD

**Issue by imperfectgrammar** [gri573/rethinking-voxels#200]
I'm running on 16 chunks, with unedited medium shader settings. 

https://github.com/gri573/rethinking-voxels/assets/121735435/aeae2276-1c54-4996-a041-7cb51c40f052

I'll give more information if needed. Idk what exactly you all need so I just took a video showing how I recreated the issue. Sorry if it isn't helpful

**Comment by kaweepatinn1** [comment]
I have the same issue. Fog or some sort of lighting thing is extremely buggy for me. Tried turning off cave fog and nothing changed so I'm assuming its not an issue with that. For me it feels like some of the blocks which emit light are being rendered and unrendered at certain distances causing changes in the fog spill

https://medal.tv/games/minecraft/clips/1lbNFLoCEjggnk/d1337ck4MKbH?invite=cr-MSwybXQsNDg0NzQxNzAs

**Comment by gri573** [comment]
fixed in the alpha versions
