### ISSUE TITLE
Light Still leaking into caves dispite the fix being on 

### ISSUE THREAD

**Issue by Huntaflamuh** [gri573/rethinking-voxels#201]
Light and godrays are still showing through caves and making caves bright like they are on the surface
![2023-07-02_00 43 30](https://github.com/gri573/rethinking-voxels/assets/110956034/924588e9-31c8-46f6-adeb-c280e8bba797)

**Comment by gri573** [comment]
that's as good as it gets in the beta versions, it is fixed on the (newer) alpha versions though
