### ISSUE TITLE
[Shaders] Error: Invalid program "composite" & "composite8"

### ISSUE THREAD

**Issue by thegoldknight** [gri573/rethinking-voxels#202]
<img width="1440" alt="Screenshot 2023-07-03 at 8 53 34 PM" src="https://github.com/gri573/rethinking-voxels/assets/135397968/b584ee46-b2a6-4420-8f2b-7acbdb813d72">
macOS M1
Java 1.19.4 Optifine

**Comment by oikbork** [comment]
I’ve been having the same issue today with macOS Java on 1.20.1 Optifine too 😞

**Comment by gri573** [comment]
use beta 18d on macOS or optifine. if that doesn't fix it, then I don't think it is possible for me to fix
