### ISSUE TITLE
Because It Is Beta It Has A Bug But Its SOO COOL!!!

### ISSUE THREAD

**Issue by gamerbenyt** [gri573/rethinking-voxels#203]
I tested this shader out because of knarfy and WOW it suprised me. Brown Terrracotta has a bug but it looks cool
![2023-07-06_08 04 02](https://github.com/gri573/rethinking-voxels/assets/136914442/2d44253b-044b-477f-b48f-287fc439463f)
![2023-07-06_08 03 56](https://github.com/gri573/rethinking-voxels/assets/136914442/9519f3e8-d291-46d8-8ac3-688aecd33730)
this shader pack w/ optifine makes a PRETTY CONVINCING RTX!!!

**Comment by gri573** [comment]
I am quite sure that is a resource pack issue
