### ISSUE TITLE
no entity shadows 

### ISSUE THREAD

**Issue by kaweepatinn1** [gri573/rethinking-voxels#206]
![image](https://github.com/gri573/rethinking-voxels/assets/37656629/8d6b01fc-cb4a-41ab-9c73-707c69de640e)
![image](https://github.com/gri573/rethinking-voxels/assets/37656629/8b1e0860-a5a4-4fee-b914-9d24d7c90f14)
title^
[rethinking-voxels_r0.1_alpha4.zip.txt](https://github.com/gri573/rethinking-voxels/files/11991037/rethinking-voxels_r0.1_alpha4.zip.txt)
config file is attached too

**Comment by Catzy44** [comment]
+1

**Comment by DarianLStephens** [comment]
Did you turn entity voxellization on in the settings?

**Comment by kaweepatinn1** [comment]
Yes, that's the reason I made this issue request.

**Comment by gri573** [comment]
entity shadows from block light are not present any more in the latest version, so this issue has become superfluous
