### ISSUE TITLE
coal not glowing glowing ores set to overworld (other ores are glowing)

### ISSUE THREAD

**Issue by kaweepatinn1** [gri573/rethinking-voxels#207]
![image](https://github.com/gri573/rethinking-voxels/assets/37656629/35636959-1a6b-4a84-a3aa-a94644471333)

**Comment by kaweepatinn1** [comment]
looks like this is identical in complimentary and probably will not be fixed

**Comment by kaweepatinn1** [comment]
wrong close

**Comment by SJK9906** [comment]
try to set "glowving ores" option to "overworld + nether"

**Comment by SJK9906** [comment]
while we waint shader update with bug correction you can try to usa "gloving ores" resourse pack and sat "PBR support" (in amin configuration page) to SEUS PBR or labPBR
