### ISSUE TITLE
Shader not loading on ultra settings

### ISSUE THREAD

**Issue by ShaderTesterForMinecraft** [gri573/rethinking-voxels#208]
composite8.fsh: composite8.fsh: ERROR: 0:784: 'sqrt' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:784: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

So, this error happens when i use the shaders on ultra settings. my graphics card is Radeon RX 6600XT, if that's needed.

**Comment by gri573** [comment]
fixed with alpha 5 or later
