### ISSUE TITLE
Light from modded blocks  only works from afar

### ISSUE THREAD

**Issue by Stormcruzerlore** [gri573/rethinking-voxels#21]
so I am running the supplementary mod which adds things like physics to lanterns that also can just be put onto the side of a wall and hung there with no supports and the light only emits from them far away up close it is dark I am not sure if the shaders have plans to support modded light? but  here is an image, if that helps, can see to the  left the ones in the distance are lit but not up close

![2023-01-10_02 51 14](https://user-images.githubusercontent.com/30479692/211650765-88a82a3b-9c74-444d-827f-4fec355259dd.png)

**Comment by zndrmn** [comment]
The ones in the distance are outside of the voxel range, so those lights are using the vanilla reimagined lighting.
The ones inside the voxel range don't know that the hanging lanterns are supposed to emit light.

**Comment by gri573** [comment]
modded lights are unsupported by me personally, but there's a special block ID (1234) in the shader's block ID mapping for additional light sources. you can just add the block IDs of your light sources to the line starting with `block.1234=` in the file `shaders/block.properties`. once you added them, you can also feel free to send me a list of block IDs (maybe as a comment on this issue) and I can add them

**Comment by Stormcruzerlore** [comment]
> modded lights are unsupported by me personally, but there's a special block ID (1234) in the shader's block ID mapping for additional light sources. you can just add the block IDs of your light sources to the line starting with `block.1234=` in the file `shaders/block.properties`. once you added them, you can also feel free to send me a list of block IDs (maybe as a comment on this issue) and I can add them

will they require a restart every time? cus theres 165 mods in the pact at least   and at least  probly 50    to 150  extra light sources

**Comment by Stormcruzerlore** [comment]
is there maybe a discord i canm join insted of cluttering the issues tab i have no idea how to  do the edits mentiond with block propertys or were to find  item IDS to adfd to them

**Comment by gri573** [comment]
yes, there is a discord: https://discord.gg/8wT5KxF4TZ

**Comment by gri573** [comment]
And you don't need to restart minecraft every time after changing that file, just press R if on iris or F3+R if on optifine to reload the shaderpack. Changing any setting also works

**Comment by gri573** [comment]
closing this as there's a guide in #35
