### ISSUE TITLE
Being in a Lush Cave causes quite a couple of darkness

### ISSUE THREAD

**Issue by rrhusdgbtbu** [gri573/rethinking-voxels#213]
https://github.com/gri573/rethinking-voxels/assets/80306366/84a2216e-6bfa-4c7f-bae5-fcc49310e4a1

any specifics about mods or hardware can be inquired, but it's mainly Minecraft 1.20.1, Quilt loader "0.20.0-beta.1"

**Comment by gri573** [comment]
fixed with latest version (I hope)
