### ISSUE TITLE
modded light sources

### ISSUE THREAD

**Issue by MNAJakov** [gri573/rethinking-voxels#214]
![2023-07-18_17 24 43](https://github.com/gri573/rethinking-voxels/assets/139891946/17c02896-c02b-4bb5-9a04-962454ef979e)
I dont know if its a bug or the shader doesnt support modded light sources

**Comment by baine1805** [comment]
I bet it has to do with the block's material. What I mean is, there likely isn't an emission texture for the block and so I'm just guessing here but I would assume that the shader doesn't see an emission texture and so therefore does not provide light. Could check my theory by creating a really basic emission texture for the block that's giving you trouble and adding it to a resource pack, or creating one just for it for testing.

**Comment by MNAJakov** [comment]
Thanks for the info. But I tried it with complementary reimagined and the lights work normally

**Comment by lumpenprol** [comment]
i too am having this issue any fix that doesn't involve editing the textures

**Comment by gri573** [comment]
mods are currently unsupported
