### ISSUE TITLE
incompatible with ocean physics from physics mod pro

### ISSUE THREAD

**Issue by gitguette** [gri573/rethinking-voxels#216]
waves do not appear, just renders water as normal

**Comment by DarianLStephens** [comment]
My guess is Reimagined added support after Voxels forked, so it doesn't have it yet without manually merging.

**Comment by 909oce** [comment]
hopefully next in the next update :D

**Comment by gri573** [comment]
physics mod hacks support into complementary, but doesn't hack support into rethinking voxels. that's completely on their end
