### ISSUE TITLE
Please, Help me with dynamic light

### ISSUE THREAD

**Issue by rodarino** [gri573/rethinking-voxels#217]
Light from objects in your hand is dynamic only while "per-pixel" mode, which is reduces my FPS in two times (I have 1660s OC). Is there any possibilities to turn on dynamic light in "per-block" mode. Sorry if I'm stupid one and cant find out, I already trying about a week and cant find this option, I'll be grateful if I can use dynamic light source with this perfect shader.

**Comment by gri573** [comment]
I don't like handheld lights, hence fixing them was never a priority. there is some version with working handheld lights in per-block mode, but I'm not sure which
