### ISSUE TITLE
is this intentional

### ISSUE THREAD

**Issue by gitguette** [gri573/rethinking-voxels#218]
if not using "pixel perfect sun shadows", the shadows of trees have strangely shaped lights. is there a fix to this? if not, is there a way to disable rendering the holes in the shadows entirely?
![2023-07-26_16 26 01](https://github.com/gri573/rethinking-voxels/assets/109386903/82ba7a23-dd18-4d05-8114-7ffb3dc9a0ca)

**Comment by SJK9906** [comment]
to fix the proble use "rethinking voxel alppha4"

**Comment by gri573** [comment]
you are using a very old version of rethinking voxels
