### ISSUE TITLE
Sunlight shining through walls

### ISSUE THREAD

**Issue by CalebAShepherd** [gri573/rethinking-voxels#22]
When I am exploring caves for instance, the sunlight tends to shine through even though it is entirely enclosed deep underground.

**Comment by NicoandLuis** [comment]
This only seems to happen at a certain depth and it's more noticable with bigger more open caves

**Comment by gri573** [comment]
the latest version has a fix for that, did you test with that?

**Comment by NicoandLuis** [comment]
Same location with current commit da9bf6d. Light leak fix is set to Full and the border fog disabled.
![2023-01-15_13 20 50](https://user-images.githubusercontent.com/3651163/212540234-6879e5fe-3b1e-4326-ae41-ab90755a1aba.png)

**Comment by gri573** [comment]
yes, I don't know how to fix that yet
I have a couple of ideas though

**Comment by gri573** [comment]
> Same location with current commit [da9bf6d](https://github.com/gri573/rethinking-voxels/commit/da9bf6d850d54e074e55d5f4ec06d02b455af184). Light leak fix is set to Full and the border fog disabled. There is no light leaking (as in sunlight which casts shadows inside the cave), but there is still bright fog. Technically it's fixed if we're just talking about sunlight.
> 
> ![2023-01-15_13 20 50](https://user-images.githubusercontent.com/3651163/212540234-6879e5fe-3b1e-4326-ae41-ab90755a1aba.png)

this is fixed too now, although someone reported the fix as broken in #28
