### ISSUE TITLE
Modding custom light sources

### ISSUE THREAD

**Issue by SinanAkkoyun** [gri573/rethinking-voxels#220]
Hey, thank you for the shaders!

I am rendering custom meshes and I need them to emit GI light as well. (I already did a lightmap implementation but RV ignores that)
How can I go about that? I am willing to fork this shader and do any modification that I need to do. Ideally, I would really like to set individual light sources from within my mod or a uniform in the shader. I am willing to dive into the code, I just need a little help on the high level approach and where to dive in :)

Thank you very much

**Comment by gri573** [comment]
I am not really knowledgeable with shader-mod interactions on the shader loader side, but I can recommend asking in the [Iris discord server](), where you will probably get support from more knowledgeable people. What you should achieve in the shader is that your custom meshes show up in the shadow pass (should usually work by default) and that they have the correct material ID assigned (as explained in #35). However, anything modded just won't work at the moment, as the latest rewrite relies on every possible block in every possible blockstate having a unique ID, and my IDs are limited to 1-16384 range. the latest version for which this still works is alpha 4

**Comment by SinanAkkoyun** [comment]
Thank you very much, my issue has beein resolved!
