### ISSUE TITLE
sourse light problem

### ISSUE THREAD

**Issue by SJK9906** [gri573/rethinking-voxels#225]
some
![Screenshot_20230804_225326](https://github.com/gri573/rethinking-voxels/assets/129201282/901712f6-ae44-4fa9-a935-22bc31abcde0)
 light sourse in hand don't emit light
![Screenshot_20230804_225256](https://github.com/gri573/rethinking-voxels/assets/129201282/fcf468c6-585f-49f3-8d32-c8fd2ebb97a5)
![Screenshot_20230804_225336](https://github.com/gri573/rethinking-voxels/assets/129201282/7bed7ced-8167-4439-8f97-52d7a0e35ed8)
![Screenshot_20230804_225344](https://github.com/gri573/rethinking-voxels/assets/129201282/e9c56ae6-2db6-48aa-8b6a-bafe3411b096)
![Screenshot_20230804_225353](https://github.com/gri573/rethinking-voxels/assets/129201282/6311bba2-3e07-4059-98e4-28f3e0dbce98)
![Screenshot_20230804_225401](https://github.com/gri573/rethinking-voxels/assets/129201282/116d2ccc-f382-4135-8a1a-328631ce4977)
![Screenshot_20230804_225409](https://github.com/gri573/rethinking-voxels/assets/129201282/e8bf360b-539f-4f16-938f-1b3610c2f9b2)
![Screenshot_20230804_225417](https://github.com/gri573/rethinking-voxels/assets/129201282/4f056a6b-721a-4817-b537-5b2f33f41bfe)
![Screenshot_20230804_225425](https://github.com/gri573/rethinking-voxels/assets/129201282/05d64c80-f930-4f27-a5af-94c756ca8851)
![Screenshot_20230804_225509](https://github.com/gri573/rethinking-voxels/assets/129201282/2aa4d50c-33ba-44d3-ba35-5b1939f3f356)
![Screenshot_20230804_225722](https://github.com/gri573/rethinking-voxels/assets/129201282/8cf1dff7-878a-4118-913b-57df9992a5fd)
![Screenshot_20230804_225732](https://github.com/gri573/rethinking-voxels/assets/129201282/507d3b55-2247-43a9-8253-e16e4fe5fa15)
![Screenshot_20230804_225740](https://github.com/gri573/rethinking-voxels/assets/129201282/c8d22309-cad9-4cdd-9e8f-9e9260f16823)
![Screenshot_20230804_225748](https://github.com/gri573/rethinking-voxels/assets/129201282/23cfb824-e824-43a7-9642-0d428ad602f0)
![Screenshot_20230804_225756](https://github.com/gri573/rethinking-voxels/assets/129201282/7a099c24-45a5-47b5-9283-cca345e49630)
![Screenshot_20230804_225803](https://github.com/gri573/rethinking-voxels/assets/129201282/67ba563e-2e53-40a2-b501-d959a014fc8f)
![Screenshot_20230804_225810](https://github.com/gri573/rethinking-voxels/assets/129201282/2590af4f-ee4b-437d-b180-02c4b8d57a03)
![Screenshot_20230804_225816](https://github.com/gri573/rethinking-voxels/assets/129201282/0dabe2b0-b7ea-4004-b547-ea368e81b24e)
![Screenshot_20230804_230710](https://github.com/gri573/rethinking-voxels/assets/129201282/c204efbd-f87f-4f36-8c07-9cf8c0096e83)

entity don't creat shadow or don't emit light (end cristal work corretly) with "entity voxelization" option set to "on"
![Screenshot_20230804_230342](https://github.com/gri573/rethinking-voxels/assets/129201282/87467086-aad6-4bd0-9799-fd6c3484b1b6)
![Screenshot_20230804_230538](https://github.com/gri573/rethinking-voxels/assets/129201282/dd33be8c-bfcd-4d6d-ad0a-300566ba1cfa)
![Screenshot_20230804_231436](https://github.com/gri573/rethinking-voxels/assets/129201282/06ad4305-7d0f-4323-a60f-cf52108bbdf7)

beacon ray don't emit light but beacon emit light
![Screenshot_20230804_230846](https://github.com/gri573/rethinking-voxels/assets/129201282/4e2e9514-092f-4ed8-8bc2-f84634e5f5d3)
![Screenshot_20230804_230944](https://github.com/gri573/rethinking-voxels/assets/129201282/23bdbe3e-3c26-4c08-846d-13312cff0ad4)

sistem information:
kernel: 6.4.7-zen1-3-zen (64 bit)
graphy platform: X11
CPU: 16 × 11th Gen Intel® Core™ i7-11700KF @ 3.60GHz
GPU: NVIDIA GeForce RTX 3060/PCIe/SSE2

> shader:
[rethinking-voxels_r0.1_alpha4.zip](https://github.com/gri573/rethinking-voxels/files/12266555/rethinking-voxels_r0.1_alpha4.zip)
shader 

> configuration:
[rethinking-voxels_r0.1_alpha4.zip.txt](https://github.com/gri573/rethinking-voxels/files/12266557/rethinking-voxels_r0.1_alpha4.zip.txt)
minecraft 

> option:
[options.txt](https://github.com/gri573/rethinking-voxels/files/12266561/options.txt)

> mons:
-fabric-api-0.85.0+1.20.1.jar
-iris-mc1.20-1.6.4.jar
-sodium-fabric-mc1.20-0.4.10+build.27.jar

> minecraft versione:
minecraft java 1.20.1

> java version:
version:8 pudate:371

**Comment by gri573** [comment]
I don't like handheld lights, and having them coloured is tedious to support, so I won't fix this unless I find a really easy way
