### ISSUE TITLE
Stair issue

### ISSUE THREAD

**Issue by Cleverpenguin666** [gri573/rethinking-voxels#226]
On stairs quartz stairs, it flickers like crazy.

https://github.com/gri573/rethinking-voxels/assets/142317985/54fd9555-4335-40c3-a061-2f9e618734a7

**Comment by aedanflynn** [comment]
I can add that its not just quartz, a number of stair types cause issues. Seems to be like they can't decide which light source they should be rendering from.
![2023-09-29_14 22 19](https://github.com/gri573/rethinking-voxels/assets/14184015/61e1460f-e6f9-468a-922d-8af2a067fb9a)
![2023-09-29_13 57 29](https://github.com/gri573/rethinking-voxels/assets/14184015/27a2397e-4d07-4a31-b0cb-c7e2db48ade4)

**Comment by gri573** [comment]
fixed in alpha 5 and later versions
