### ISSUE TITLE
[1.20.1 Fabric] Incompatiblity with Litematica when using Per-Pixel mode.

### ISSUE THREAD

**Issue by NukelordPvP** [gri573/rethinking-voxels#227]
When I enable any instances of Per-Pixel mode while a litematic is loaded a black fog starts expanding once i look at the litematic on my screen and spams logs with errors.
[latest.log](https://github.com/gri573/rethinking-voxels/files/12373346/latest.log)
With per-pixel:
![2023-08-17_13 28 44](https://github.com/gri573/rethinking-voxels/assets/63741267/197ac64a-4285-4bd2-9168-ad884dc67872)
![2023-08-17_13 28 24](https://github.com/gri573/rethinking-voxels/assets/63741267/61481bd7-8594-4c10-86dd-ddff52a5075a)
Without per-pixel:
![2023-08-17_13 28 53](https://github.com/gri573/rethinking-voxels/assets/63741267/81ab2e79-ee3b-4062-bb07-f6e496cb0341)

**Comment by gri573** [comment]
probably fixed in the rewrite
