### ISSUE TITLE
Fishing Black Fog Bug (1.20)

### ISSUE THREAD

**Issue by Khriptinn** [gri573/rethinking-voxels#228]
Whenever I go fishing, or sometimes this will randomly happen while playing, some weird black fog starts covering the screen until it's entirely black... Although the fishing rod is modded, I tested this with a regular minecraft fishing rod and it duplicates the same effect. I'll upload my shader settings alongside a video recreation...

Shader Settings:
[rethinking-voxels_r0.1_alpha4.zip.txt](https://github.com/gri573/rethinking-voxels/files/12399581/rethinking-voxels_r0.1_alpha4.zip.txt)

Video:
https://medal.tv/games/minecraft/clips/1q6Ei4CDo5Mcji/d1337FGITHNU?invite=cr-MSxCUGssMTI5NzIwNDIxLA

**Comment by DataDalton** [comment]
I noticed this is other things as well, for example just walking around/moving can make it occur, no need to fish. Fortunately, it doesn't seem to happen often to me/only happened the first time I launched Minecraft with the shader
