### ISSUE TITLE
Invalid staircase shadows

### ISSUE THREAD

**Issue by jeffswt** [gri573/rethinking-voxels#23]
The stairs shouldn't have shadows like that. Is it that the stair model being used for ray tracing is invalid?

![image](https://user-images.githubusercontent.com/18145331/212390361-b6b70b5c-2bc4-46eb-a08b-ec04b01cb494.png)

**Comment by gri573** [comment]
the stairs just use slab models for now, when I change that, I would like to do it in a way that detects the orientation automatically, but I don't know how to do that yet.

**Comment by gri573** [comment]
this is fixed with accurate RT in the latest version
