### ISSUE TITLE
Rethinking Voxels Shaders don't work

### ISSUE THREAD

**Issue by Nikaalex** [gri573/rethinking-voxels#230]
After installing the shaders, the following error appears. Shaders don't work. I don't understand how to fix
![Rethinking Voxel Shaders dont work](https://github.com/gri573/rethinking-voxels/assets/70762033/64409855-a884-4981-a314-dc7f464536a9)

**Comment by vistis** [comment]
Update Iris

**Comment by gri573** [comment]
use iris, not optifine
