### ISSUE TITLE
QoL: Adding an Option to adjust the amount of tint of stained glass

### ISSUE THREAD

**Issue by GERZAC1002** [gri573/rethinking-voxels#231]
While testing different shaders i noticed how the tint of stained glass changed and i prefer it to be more intense and i couldn't find a shader setting to change it.  I tried setting the FANCY GLASS(after removing the IRIS condidiont from shaders/lib/common.glsl) as well as the GLASS_OPACITY(only applied to normal Glass) Option but it made no difference. I also tried to edit "shaders/lib/materials/specificMaterials/translucents/stainedGlass.glsl" my self and played around with some values, but because i don't have knowledge about opengl shaders i didn't made any progress. So i propose a setting for changing the intensity of the tint of glass, unless it is already implemented and i am unable to find it.

Tested with:
Minecraft Version: 1.18.2
Iris Version: 1.6.6
Sodium Version: 0.4.1

Here are some examples of the difference of the intensity accross different shaders:
Rethinking-voxels:
![rethinking](https://github.com/gri573/rethinking-voxels/assets/42998799/c9ac9756-f9a8-45f9-b30b-31f08d145613)
SEUS Renewed:
![seus_renewed](https://github.com/gri573/rethinking-voxels/assets/42998799/3a81a93b-3caf-4697-a378-24f350a50f04)
Soft Voxels:
![soft_voxels](https://github.com/gri573/rethinking-voxels/assets/42998799/aa175771-ac88-4f37-8b76-7bbbc2de7935)

**Comment by gri573** [comment]
this is an inherent consequence of the way complementary (and by consequence also rethinking voxels) blends translucent colours. changing it would mean breaking some cases with multiple translucent layers such as stained glass in front of water etc (at least I think it would). furthermore, changing this would mean directly interfering with complementary's codebase in an additional location, and that would make it more difficult to update to new complementary versions in the future. as such I don't want to add a setting for stained glass blending mode
