### ISSUE TITLE
[FramedBlocks] Lighting issue

### ISSUE THREAD

**Issue by DataDalton** [gri573/rethinking-voxels#233]
I am working on adding lighting to the framedblocks blocks, however, there's is a little problem. 

You can right click any of the framedblocks with a piece of glowstone and it makes it have light (it doesn't by default, so just adding the `framedblocks:framed_cube` to block properties doesn't work), it doesn't transform the id of the block it just adds nbt data to it, `"glowing": "0b"` to `"glowing": "1b"` is there anyway to specify this in the current block.properties?

**Comment by gri573** [comment]
yes, the id you need to add then is `framedblocks:framed_cube:glowing=1b`
