### ISSUE TITLE
[Feature request] Custom block color specification

### ISSUE THREAD

**Issue by DataDalton** [gri573/rethinking-voxels#235]
Currently, the community is able to put any block id as equal to block `1234`, and it uses the default white glow, we also have `1235` as fallback colors but seem unused. Is it possible to allow us to set custom modded blocks to have default glows? 

For example, block `1236` is Aqua, hex #00FFFF and block `1237` is Light Blue, and we continue for most of the common colors and if something doesn't exactly fit we just match it to the closest. An example of this in the block.properties would look like this:

block.1234=

#Fallback
block.1235=

#Aqua Hex: #00FFFF
block.1236=

#Light blue Hex: #ADD8E6
block.1237=

I understand currently block 1234 says `#automatically determine blocklight colour`, but it seems to either not do it well or just not work to my understanding of how it should be (emitting a glow based off of the glowing color of the block) and just does white/some shade of white

**Comment by Akashsingh310** [comment]
Yes, it is possible to allow custom modded blocks to have default glows by specifying their glow colors in the block.properties file. You can assign specific colors to block IDs like this:

```
block.1234= # This could be the default color for block 1234
block.1235= # This could be the default color for block 1235
block.1236= # This could be the color for block 1236 (Aqua)
block.1237= # This could be the color for block 1237 (Light Blue)
```

**Comment by DataDalton** [comment]
> Yes, it is possible to allow custom modded blocks to have default glows by specifying their glow colors in the block.properties file. You can assign specific colors to block IDs like this:
> 
> ```
> block.1234= # This could be the default color for block 1234
> block.1235= # This could be the default color for block 1235
> block.1236= # This could be the color for block 1236 (Aqua)
> block.1237= # This could be the color for block 1237 (Light Blue)
> ```
> 
> 
> 

Sorry, I meant this as less of a question if it's possible, but more of a feature request to the shader developer, as I'm not sure how exactly it'd have to be implemented in its current state

**Comment by gri573** [comment]
it is possible, but my first issue is getting mod support back at all, so I'll close this as it is not relevant yet
