### ISSUE TITLE
Firework particles use shader effects far away rather than close up, should be both or just close up, beta18d

### ISSUE THREAD

**Issue by MichaelDawe** [gri573/rethinking-voxels#237]
![2023-09-16_15 37 36](https://github.com/gri573/rethinking-voxels/assets/75983563/d2c4c5b6-8789-40e8-b142-baeb0bcfcf54)
![2023-09-16_15 37 44](https://github.com/gri573/rethinking-voxels/assets/75983563/8a117677-ec3b-49a5-bd30-14541560672d)

**Comment by DarianLStephens** [comment]
Anything that's 'close up vs far away' in this shader is 99% going to relate to the voxellization.
I don't know what you mean about firework shaders. Is that what it does for brightness and color? I thought that was general openGL stuff?

**Comment by MichaelDawe** [comment]
Because they're particles and don't affect lighting or anything else in the would I would imagine its not related to voxelization, however I don't know how this shader really works.  Yes, the shader makes the particles emissive (light up) and adds bloom and twinkling effects.  For performance reasons this is usually only applied close to the player, as you can see in my screenshots it is instead being applied further away and the default Minecraft (not emissive) particles are rendered closer.  I believe this is a bug.

**Comment by gri573** [comment]
I can't really detect particle emission.

**Comment by MichaelDawe** [comment]
Particles work correctly in the original Complementary shaders, perhaps they could be left unchanged by your modifications?  They have their own shader filenames, "gbuffers_textured_lit" I think.
