### ISSUE TITLE
Light blocks arent emitting light

### ISSUE THREAD

**Issue by BCAtoolong** [gri573/rethinking-voxels#25]
I tried it out because it looked awesome in the picture and videos, but to my disappointment, when i loaded up my world, it was just really dark and no light was coming from anywhere. the moon was creating some shadows but then they would glitch away..

**Comment by NicoandLuis** [comment]
Do you have a screenshot on how it looks for you?

**Comment by BCAtoolong** [comment]
I just reinstalled it and it worked. I also took off a Fullbright resourcepack which i had on. I didnt get a screenshot, but it works now so..

**Comment by gri573** [comment]
that may very well have been the fullbright resource pack messing with something, glad it fixed itself
