### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by JohJakob** [gri573/rethinking-voxels#250]
Whilst Complementary Reimagined does work pretty well on macOS, Rethinking Voxels does not work at all currently (at least on my system).

I would love to see macOS support, even though I can imagine that it might be a huge challenge.

---

Operating System: macOS 14 Sonoma
CPU + GPU: Apple M1 Max (Apple Silicon)
RAM: 32 GB

**Comment by gri573** [comment]
more specifically, rethinking voxels needs modern openGL features to do its lighting effects, which are not available on MacOS

**Comment by JohJakob** [comment]
That is unfortunate, but I am still looking forward to seeing this project progress :)

**Comment by gri573** [comment]
glad to hear that :)
