### ISSUE TITLE
Intense flickering with light emitting from lava

### ISSUE THREAD

**Issue by CalebAShepherd** [gri573/rethinking-voxels#26]
Light that comes from lava flickers much more than any other blocklight.

**Comment by zndrmn** [comment]
try turning on the color override for lava

**Comment by gri573** [comment]
Light colour is supposed to update instantly with texture colour for animated textures. that can, as zndrmn suggested, be changed by turning on "override lava colour". Is there more flickering than usual remaining after enabling that?

**Comment by CalebAShepherd** [comment]
> Light colour is supposed to update instantly with texture colour for animated textures. that can, as zndrmn suggested, be changed by turning on "override lava colour". Is there more flickering than usual remaining after enabling that?

I turned color override on but it did not change the flickering. This might be silly but could it have something to do with the fact that lava is much brighter than the other blocklights?

**Comment by CalebAShepherd** [comment]
@gri573 since the Fix Flickering update the flickering on lava has gotten significantly better, it barely ever flickers now. There are a few spots here and there that still flicker sometimes but not nearly as much as before.

**Comment by gri573** [comment]
Ok, I'll close this issue then
