### ISSUE TITLE
Dark Night

### ISSUE THREAD

**Issue by RoflTom** [gri573/rethinking-voxels#278]
In older versions i was able to make the night completely dark by setting the light multiplier for nighttime to minimum.
Now this is what i get:
![MC](https://github.com/gri573/rethinking-voxels/assets/36345470/6fc06c72-12cb-48c6-8bfe-caa7ef7daf58)
Am i missing something or is something broken here?

**Comment by gri573** [comment]
GI is slightly broken, you can turn it off. the GI issue is tracked elsewhere, so I'll close this
