### ISSUE TITLE
Light in a large cave 

### ISSUE THREAD

**Issue by Drafothedragon** [gri573/rethinking-voxels#28]
There seems an issue that if i'm in a large cave the light rays comes thought the walls, hope the picture explains everything 
I'm using the Rethinking Voxels Beta 13a version
![2023-01-21_21 45 34](https://user-images.githubusercontent.com/68086287/213886518-0f73b8fd-b634-4c32-b74b-840af09cf676.png)

**Comment by gri573** [comment]
just in case: did you turn off the cave sunlight fix?

**Comment by gri573** [comment]
Closing this due to lack of feedback
