### ISSUE TITLE
Dynamic handheld lighting and per pixel light calculation not working

### ISSUE THREAD

**Issue by SirLordCandice** [gri573/rethinking-voxels#288]
I tried to turn on dynamic handheld lighting and it said to turn on per pixel light calculation and when I did dynamic lights still don't work and per pixel light calculation makes block lighting and particles look horrible.

**Comment by gri573** [comment]
dynamic lights will be improved in the next version (already better on the repo), "horrible" is subjective and definitely not constructive criticism
