### ISSUE TITLE
Crash with Physics mod Pro [CRASH]

### ISSUE THREAD

**Issue by OceanFifty** [gri573/rethinking-voxels#294]
The crash is reproduced when real-time shadows are turned ON, and the player breaks blocks or generates the world. Error code give in log is STATUS_STACK_BUFFER_OVERRUN. This is the only shader crashing with physics mod that I tested, but not sure which is causing the crash.

Game version: 1.20.1
Fabric loader 0.15.6
Physics mod Pro 166b (1.20.1)
Sodium 0.5.7 (1.20.1)
Fabric api 0.91.0 1.20.1)
iris 1.6.15 (1.20.1)

**Comment by gri573** [comment]
Physics mod is unsupported, as it needs to hack into shaders to work, and supporting it from the shader side is possible, but requires more effort than I'm willing to put into it, as this effort is better spent elsewhere IMO.
