### ISSUE TITLE
Uhhh what is that????

### ISSUE THREAD

**Issue by mikhailfluffy** [gri573/rethinking-voxels#303]
![image](https://github.com/gri573/rethinking-voxels/assets/79972291/ab232616-b6fe-4ced-8b9b-e248312f06c4)

This shader breaking my game after I turn on it.
Using Last OptiFine-Compatible Version] Beta 18d

**Comment by gri573** [comment]
this is an optifine bug that happens in some optifine versions, most common when loading it via forge rather than standalone. not related to rethinking voxels.
