### ISSUE TITLE
Light is emitted only from the center of a block

### ISSUE THREAD

**Issue by Clozent** [gri573/rethinking-voxels#304]
~When using LabPBR with a supported resource pack,~ Blocks that emit light do so only from the center of the block, and not from the light emitting pixels on the surface. ~This does not happen with the Integrated PBR+ option.~

This is most obvious when the Light Source Size setting is set to 0 (Like in the example below).

Edit: I just realized: The light is emitted from the center regardless, it's just that the Integrated PBR+ makes all of the block emit light. This means the problem applies to the entire shaderpack, not just to it's LabPBR implementation. It's just more obvious with LabPBR.

With Integrated PBR+:
![2024-02-21_17 35 14](https://github.com/gri573/rethinking-voxels/assets/45975432/e70e7b9d-e0e1-4f33-b40d-b1d0cc7eb000)

With LabPBR:
![2024-02-21_17 30 56](https://github.com/gri573/rethinking-voxels/assets/45975432/633354fa-fc08-48d5-8801-ab7328d5115f)

**Comment by gri573** [comment]
this is intended. it is part of the visual style of the shaderpack
