### ISSUE TITLE
Weird after image and shadow rendering (1.20.2 fabric)

### ISSUE THREAD

**Issue by Narrowlegacy87** [gri573/rethinking-voxels#305]
I don't know whats causing this and it seemed to come out of nowhere but looking around causes a strange after image like effect on all entities and some tiles along with weird shadow rendering where if I look away from a certain area and look back the shadows will rebake themselves rather than staying baked.

What can I do to fix this? Is this a bug with Iris?

Here is a video of what I am experienceing and yes I have Indium 

https://github.com/gri573/rethinking-voxels/assets/63093346/160ae45e-d92a-461e-a8d4-770abcddb77c

**Comment by Narrowlegacy87** [comment]
oh yeah I'm using r0.1 beta2

**Comment by gri573** [comment]
this is unfixable until iris adds velocity information
