### ISSUE TITLE
sun shadow filtering

### ISSUE THREAD

**Issue by bonbox2531** [gri573/rethinking-voxels#31]
Minecraft 1.19.2
shader version last
iris1.5
sodium0.4.4
![2023-01-25_07 43 30](https://user-images.githubusercontent.com/123515921/214442145-d17ff4e7-718c-431a-a16d-2b5848e60a81.png)
Can you correct this one?
Also, is it possible to add an option for shadow drawing distance?

**Comment by gri573** [comment]
sun shadow distance ties into the voxelisation distance, which depends on voxel volume size and height. it cannot account for anything outside of the voxel volume anyway, so there's no point in making it bigger. making it smaller could be useful if you want sharper shadows. I'll add a very small sun path rotation to fix the issue with leaf shadows (small enough to be almost unnoticable.

**Comment by gri573** [comment]
this has been slightly improved in the latest commit, another thing you could do to fix it is playing at a time other than noon
