### ISSUE TITLE
Lighting not smooth when moving blocks/entities

### ISSUE THREAD

**Issue by Dagherbou** [gri573/rethinking-voxels#4]
Lighting is blocky and not smooth when its emitting from block with animations or from entites, I know its normal but will you eventually fix it or is it not possible ?

**Comment by gri573** [comment]
There is now a "basic light propagation" mode, which fixes that, but doesn't have sharp shadows. fixing it completely is not really possible, but I'm trying to make it less jarring.

**Comment by gri573** [comment]
it should be much better with instant light propagation
