### ISSUE TITLE
Entities don't have shadows

### ISSUE THREAD

**Issue by Ninjaabdullah** [gri573/rethinking-voxels#40]
Entities (Mobs, Players, Items) don't have shadows when under the sunlight

Complementary Reimagined
![2023-01-30_20 19 12](https://user-images.githubusercontent.com/110191900/215563422-936f2d55-e910-4591-ba67-b68b0bd192bc.png)
Rethinking Voxels Beta 15
![2023-01-30_20 19 25](https://user-images.githubusercontent.com/110191900/215563459-b352c315-bb00-4708-838f-2a9374fb3439.png)
Complementary Reimagined
![2023-01-30_20 20 12](https://user-images.githubusercontent.com/110191900/215563505-d3475510-9fb5-4740-8528-4746d43d63a6.png)
Rethinking Voxels Beta 15
![2023-01-30_20 20 21](https://user-images.githubusercontent.com/110191900/215563370-22c3a9cd-4a17-444e-b830-ddcba837eb0a.png)

**Comment by gri573** [comment]
That's impossible to fix sadly
