### ISSUE TITLE
No PBR support

### ISSUE THREAD

**Issue by Althyrios** [gri573/rethinking-voxels#41]
PBR function is not working with PBR texture pack
Exemple:
Astralex shader with PBR activated:
[https://www.zupimages.net/up/23/05/u2tn.png](url)
Rethinking voxel with PBR  activated:
[https://www.zupimages.net/up/23/05/iswj.png](url)

**Comment by zndrmn** [comment]
PBR doesn't exist on Reimagined 1.4
PBR is coming to Reimagined 2.0 which is currently under development

**Comment by gri573** [comment]
this is added since beta 18 / complementary reimagined r2.0
