### ISSUE TITLE
ZOOM

### ISSUE THREAD

**Issue by eidosik** [gri573/rethinking-voxels#42]
Hi, ZOOM function from OptiFine not working with Rethinking Voxels shader....

**Comment by gri573** [comment]
That's very unlikely to be caused by the shader, did you try if it works with other shaders?

**Comment by jeffswt** [comment]
Generally Zoom is implemented by changing the FoV, so if you're able to change the FoV but can't zoom, there's a 90% chance that the issue is not about the shader.

**Comment by gri573** [comment]
I'll close this since it's probably not a shader bug

**Comment by eidosik** [comment]
other shaders work normally... only this shader. Others that I have support zooming only on overworld, nether or both ...

**Comment by gri573** [comment]
You could use iris and logical zoom or some other zoom mod then

**Comment by eidosik** [comment]
thanks, i try it... does the Iris also have a zoom function ?? like a OptiFine???

**Comment by kaxlabs** [comment]
> thanks, i try it... does the Iris also have a zoom function ?? like a OptiFine???

No, but you can always grab the features from other mods like LogicalZoom.
