### ISSUE TITLE
Less volumetric fog (BAD)

### ISSUE THREAD

**Issue by lynrayy** [gri573/rethinking-voxels#43]
Please turn back this juicy fog! Also beta 16 less performance that beta 11 (70fps vs 50-55)
beta 11:
![image](https://user-images.githubusercontent.com/59417884/215976757-28ff8eb7-2539-4ab3-829f-7caa6a685e16.png)
beta 15
![image](https://user-images.githubusercontent.com/59417884/215976790-d84339f2-d3e1-4c08-aaf6-8a3dc1068d22.png)

Another
beta 11:
![image](https://user-images.githubusercontent.com/59417884/215976983-0ccaf3db-928e-4e55-8f97-169ae15c4580.png)
beta 16:
![image](https://user-images.githubusercontent.com/59417884/215977027-7f861e20-46cf-498d-884d-21f1d90036d7.png)

**Comment by zndrmn** [comment]
there are options to adjust the fog

**Comment by zndrmn** [comment]
also the worse performance is because the default voxel volume size was raised iirc

**Comment by lynrayy** [comment]
> there are options to adjust the fog

Ok, where is it? And how to return old lighting like here? 
old:
![image](https://user-images.githubusercontent.com/59417884/215978135-f1c7b765-a424-4797-98bf-2f18848507aa.png)
new:
![image](https://user-images.githubusercontent.com/59417884/215978190-844f3c43-ff3e-410d-b9f8-64721b7257f6.png)

**Comment by lynrayy** [comment]
I really don't like new lighting. It looks more flat

**Comment by zndrmn** [comment]
Voxelisation Settings > Volumetric Blocklight Strength 
the old value was like 1.0 or something

**Comment by lynrayy** [comment]
Ok. And where and what value i should set for  _**default voxel volume size**_

**Comment by zndrmn** [comment]
This will make your game look a lot worse but the old values for voxel volume size and voxel volume height were Low & 36

**Comment by lynrayy** [comment]
It's ok, i just want my FPS back

Somehow pathtraced SEUS goes faster on my pc than last beta of RV :(

Will try your preferences

**Comment by lynrayy** [comment]
How can i get back this back lighting?
Beta 16
![image](https://user-images.githubusercontent.com/59417884/216153336-ca359d3d-9df2-42c9-8672-c86b55d3c88e.png)

Beta 11
![image](https://user-images.githubusercontent.com/59417884/216153637-c3528b62-6920-419d-b169-b36130998080.png)

**Comment by gri573** [comment]
Increase volumetric blocklight strength in shader option -> voxelisation settings, the old default value was 0.5

**Comment by lynrayy** [comment]
Already set to 0.5

How to return back lights?

**Comment by gri573** [comment]
The only difference I see there is the cave sunlight fix not working in beta11, you can disable cave sunlight fix in voxelisation options to change that

**Comment by gri573** [comment]
Ah, do you mean the incorrectly bright fog in the distance? That has been fixed and i won't make an option to disable the fix

**Comment by lynrayy** [comment]
Shame
It was very cinematic.
