### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lynrayy** [gri573/rethinking-voxels#48]
make an option to disable the fix
 
 Without fix 
![image](https://user-images.githubusercontent.com/59417884/216316112-cb33833e-6911-4a67-97dc-5dffd4a96210.png)

With fix 
![image](https://user-images.githubusercontent.com/59417884/216316129-f947f155-718a-42f2-b97c-88548e65fc39.png)

**Comment by lynrayy** [comment]
most people?
Don't speak for everyone.
Those people to whom I showed a comparison of new and old shaders said that the new ones are worse (5 minecraft guys)

**Comment by lynrayy** [comment]
Everyone is excited about these shaders and it really looks like a revolution. But in this case it's a downgrade

**Comment by gri573** [comment]
Look, I received multiple bug reports about it being bright (here and on discord), and yours is the first one about it being dark

**Comment by lynrayy** [comment]
You can make it optional

**Comment by gri573** [comment]
I can, but it's another option to keep track of, adding development complexity and longer loading times, while I personally don't see how it contributes positively to visuals. I won't add it as an option.
