### ISSUE TITLE
Intense flickering with fire

### ISSUE THREAD

**Issue by CalebAShepherd** [gri573/rethinking-voxels#51]
Same as the lava issue but it is occurring with fire too. The lava flickering has been mostly fixed but fire still flickers a lot.

**Comment by gri573** [comment]
Enable override fire color in shader options -> preference setting -> lighting -> light colors -> fire

**Comment by gri573** [comment]
Actually, that might not fix it if it is related to #26

**Comment by gri573** [comment]
this should be fixed in the rewrite
