### ISSUE TITLE
Modded Trapdoor Lighting Bug

### ISSUE THREAD

**Issue by oliwh** [gri573/rethinking-voxels#52]
When using trapdoors from mods, opening the trapdoor the inside of the block area to appear dark. The outside of the trapdoor appears normal and when the trapdoors are in a closed state they also appear normal. 

![image](https://user-images.githubusercontent.com/50079382/216729125-62236fd0-b9ae-4d8b-9159-8841520970fa.png)

**Comment by gri573** [comment]
That's not fixable unless you want modded full blocks to not cast any shadows
