### ISSUE TITLE
Messed up lighting.

### ISSUE THREAD

**Issue by NaryComeHome** [gri573/rethinking-voxels#54]
When using the most recent Rethinking Voxels with the newest Optifine preview version, I loaded into my world and found that only hand lighting and sun lighting works.

![2023-02-03_19 10 05](https://user-images.githubusercontent.com/124411841/216738048-f7f6f667-2073-4298-921e-1544e3624b63.png)

**Comment by gri573** [comment]
You could use iris, i generally don't support preview versions of optifine (iris previews are fine because the iris devs are very good at giving me feedback on whether or not something is an iris bug or a shader bug). Did it work on optifine H9 for 1.19.2?

**Comment by gri573** [comment]
I'm closing this for now, will reopen if you come back to me with more information
