### ISSUE TITLE
Shadows from light sources are broken on 1660Ti Mobile

### ISSUE THREAD

**Issue by LatifSC** [gri573/rethinking-voxels#56]
Indoor shadows are glitching and smoothing effect breaks on 1660ti. And any time i walk the shadows are changing direction aswell (indoors). I've tried my modpack, map and version on my brothers laptop which has Vega 7 in it. It couldn't handle but it was what it should look like. I've used Iris 1.5 and Adoptium on both PCs.

My system:
Ryzen 7 3750H
Gtx 1660Ti
8x2 2400mhz RAM
Nvidia Game Ready 528.24 Driver

My brothers:
Ryzen 5 5500U
4x2 2400mhz RAM
Vega 7 iGPU
Latest modded Huawei Radeon Driver

![2023-02-05_00 47 40](https://user-images.githubusercontent.com/68355853/216791272-87240dd7-bd3a-4a06-b81b-21cf954b200f.png)
![2023-02-05_00 47 57](https://user-images.githubusercontent.com/68355853/216791281-b5877a15-8980-44a5-8cdd-22bd89094a60.png)
![2023-02-05_00 48 00](https://user-images.githubusercontent.com/68355853/216791283-e172b954-3ebd-4a45-900e-79b1ee95b4f1.png)
![2023-02-05_00 48 05](https://user-images.githubusercontent.com/68355853/216791285-a9bf4215-eb21-4941-8b10-8da864e74cb7.png)
![2023-02-05_00 48 17](https://user-images.githubuse
![2023-02-05_00 48 22](https://user-images.githubusercontent.com/68355853/216791291-20cf16eb-649d-420c-a243-bc71bdf8a269.png)
rcontent.com/68355853/216791289-538790a4-89f3-4d5d-ab6f-9d111496a6d4.png)

**Comment by gri573** [comment]
The bed's shadow flickering like that is something that I was hoping to have fixed, and it should only happen when not close to world spawn ((x, z) = (0, 0)). I don't see how it could be hardware dependent. Is that a modded bed type or only a resource pack?

**Comment by gri573** [comment]
The black lines are also a bug that I thought I had fixed a few versions ago

**Comment by LatifSC** [comment]
Its a resource pack but happens without aswell. I've tried the latest version. It fixed the bed and lines issue. However, the performance is worse and theese shadow/lighting bug still exists. In older versions they were smooth. The shadows on the outside are normal. They appear on Optifine with or without mods aswell.
And you're right. I tested with Vega 10 gpu and results are the same. 
![2023-02-05_17 17 45](https://user-images.githubusercontent.com/68355853/216826221-f31ea79d-ab6b-4cbc-a8d3-bd83ea10adb1.png)
![2023-02-05_17 17 51](https://user-images.githubusercontent.com/68355853/216826426-1ff9a52a-7239-40b9-ab5c-8145d7a40a03.png)
![2023-02-05_17 17 53](https://user-images.githubusercontent.com/68355853/216826435-f54d6896-53b7-4699-bbc5-a4865ff265cc.png)
![2023-02-05_17 31 38](https://user-images.githubusercontent.com/68355853/216826439-d1b5130b-c5fe-4d5b-8304-01a90bc0ecad.png)

**Comment by gri573** [comment]
you can make the shadows smoother by disabling the occlusion bleeding 'fix' in voxelisation settings, but that will cause some other lines, or by enabling pixel perfect blocklight shadows. The last picture shows a problem I can't really fix for now and which has become more visible recently in some cases. the shadow on the wall is just the shadow of one lantern cast by the light coming from the other lantern though, so that's correct. I increased some default settings at some point, the old default settings are roughly equivalent to the current medium profile. that could be where some of your performance went.

**Comment by LatifSC** [comment]
Making these changes fixes lighing but pixel perfect shadows ruins the games and shaders theme for me. I guess I'll have to play with these artifacts. This shader looks so much better and natural than any other shaders

**Comment by gri573** [comment]
if you are fine with pixelated shadows, then I recommend setting occlusion filter to off in voxelisation settings, it will yield a significant performance improvement

**Comment by LatifSC** [comment]
Thanks but turning off occlusion filter makes light go through opaque blocks. Also, Exline's Furniture mods Light doesn't emmit light. I dont know if it is mods or shaders issue but i wanted to report. 
![2023-02-05_18 23 39](https://user-images.githubusercontent.com/68355853/216828398-5cc6e23e-b6ab-487c-a805-66686f1920be.png)

**Comment by gri573** [comment]
You can see #35 for modded light support
