### ISSUE TITLE
leaves do not make any shadow light just passes through them

### ISSUE THREAD

**Issue by emceeweeb** [gri573/rethinking-voxels#57]
i didnt mess with the setting but it light just passes through the leaves without any form of dimming

**Comment by gri573** [comment]
![image](https://user-images.githubusercontent.com/66473137/216827774-36e35d5a-dd36-4565-b2e2-a39ab6c92a35.png)
it works fine on my end

**Comment by emceeweeb** [comment]
well specifically sun light ill send a ss in a sec

**Comment by emceeweeb** [comment]
![2023-02-05_18 14 02](https://user-images.githubusercontent.com/124476668/216851434-7dfbf8fb-8147-4529-bcc9-b429907ef0a4.png)
its caused from other texture packs

**Comment by emceeweeb** [comment]
![2023-02-05_18 27 44](https://user-images.githubusercontent.com/124476668/216852056-a3ce83b5-ad40-4821-8aa4-5e3a397cd79e.png)
this is also happening camfires aren't having correct lighting

**Comment by gri573** [comment]
the leaves look like they're working in the last screenshot you sent though

**Comment by gri573** [comment]
if this still occurs, then it is caused by something else than previously
