### ISSUE TITLE
Glowstone causes black glitches.

### ISSUE THREAD

**Issue by CarlTheObeseCat** [gri573/rethinking-voxels#59]
<img>https://i.imgur.com/IZwq498.jpg</img>
As you can see glowstone causes these werid lighting issues that no other light blocks seem to cause.

**Comment by gri573** [comment]
I don't see any black glitches in that picture, but it also has a pretty low quality, as though it had been heavily compressed... You can also embed images directly into github issues via drag-and-drop

**Comment by LatifSC** [comment]
I think he is talking about the noise. Looking at fps his gpu probably cannot render fast enough. Maybe I'm wrong but this happens with games with ray tracing implemention on weak gpus.

**Comment by gri573** [comment]
ok, you can disable pixel perfect blocklight shadows to get rid of the noise

**Comment by gri573** [comment]
I'll close this issue, but if you think I misunderstood you and there's a different issue shown in your screenshot, then leave a comment and I'll reopen it
