### ISSUE TITLE
Nothing gets rendered

### ISSUE THREAD

**Issue by DankstoneMC** [gri573/rethinking-voxels#60]
https://user-images.githubusercontent.com/90248925/216812158-7ed7b8a1-2249-4fa3-82e8-ce581c32e1ef.mp4

In my case, absolutely nothing gets rendered when I turn on this shader pack. Could be some weird thing with my system

**Comment by gri573** [comment]
That's probably a mod conflict. Did you try without mods?

**Comment by DankstoneMC** [comment]
Does seem to work with only sodium and iris

**Comment by DankstoneMC** [comment]
And apparently still works fine after putting all of the mods back in

**Comment by gri573** [comment]
ok, I'll close this issue then. glad it worked out
