### ISSUE TITLE
when diving the lighting changes at some point abruptly

### ISSUE THREAD

**Issue by kornypa** [gri573/rethinking-voxels#61]
![2023-02-05_23 30 33](https://user-images.githubusercontent.com/123405598/216849758-841163f7-c312-4fa8-b93a-535e6ff35d0d.png)
![2023-02-05_23 30 26](https://user-images.githubusercontent.com/123405598/216849761-a1d540d4-0aaa-439f-b127-e36022b1f181.png)

it seems to happen in the y-block range from 51-50 (51.40-51.10)

**Comment by gri573** [comment]
that's fixed in the latest beta (beta16)
