### ISSUE TITLE
Lantern will not work until you're far away

### ISSUE THREAD

**Issue by BlazingKaiser** [gri573/rethinking-voxels#62]
I've search this up and it seems like someone else actually reported this problem too, but lantern not working within voxel range kind of kills the vibe for me because I put up lanterns in my house so I won't be seeing ugly torches on the ground everywhere, yet due to this issue I can only use torches for light right now. I've tried adding lantern into block.1234 as minecraft:lantern, minecraft:lantern:lit=true, minecraft:lantern_lit, minecraft:lantern_lit=true, lantern, lantern:lit=true, lantern_lit, lantern_lit=true, and I've even try putting it in the same category as torch(block.10496), jack_o_latern(block.10396), none of them work, I also found out that there is a category for lantern but for whatever reason I guess it's not working, it's block.10560 which has lantern and a couple of mcwlights, but clearly they're not working for me. I've been at it for the past 2 hours and I really can't think of anything else that I can do beside asking for help in here.

https://user-images.githubusercontent.com/92186992/216857409-eb43c049-2d01-4559-8caf-663b3010a184.mp4

**Comment by gri573** [comment]
do you have physics mod or any mod that alters how lanterns work? (like making them wave or anything like that)
Those mods often break the block ID mappings and there isn't really anything I can do about it

**Comment by BlazingKaiser** [comment]
Now that you mentioned it, yeah, I do have physic mod, I guess that's why the lantern didn't work, thanks for answering.

**Comment by zndrmn** [comment]
You could probably just disable the waving lanterns and it should work fine

**Comment by gri573** [comment]
ok, I'll close this, but if you feel like it isn't resolved yet, please do comment about your concerns and I'll reopen the issue
