### ISSUE TITLE
Interferes with FancyPants texture shader [1.19.3]

### ISSUE THREAD

**Issue by approved** [gri573/rethinking-voxels#63]
Rethinking Voxels shader prevents texture packs using [Fancy Pants](https://github.com/Ancientkingg/fancyPants) shaders for custom armor textures.

Instead of seeing the custom textures, I see strings.

This is occurring on Minecraft version 1.19.3. I am unsure of previous game versions.

I am using the `Fabulously Optimized v4.6.0-beta.6 (Beta)` modpack. Installed via a new MultiMC Modrinth Instance

**Comment by gri573** [comment]
yes, using custom shaders along with iris/optifine shaders is generally a bad idea and is bound to lead to incompatibilities. I don't think I can fix that.
