### ISSUE TITLE
Too Bright on default settings

### ISSUE THREAD

**Issue by ZorkIsEmo** [gri573/rethinking-voxels#67]
i had alot of struggle enjoying the shader pack just because sands and wheat were so blinding and on some resource packs other crops, so i was switching between packs depending where i was, and it took my so long to figure out that you can turn down the white tone mapping to fix this if you dont like it like me, i HIGHLY recommend changing the default settings for new users of the pack because it is VERY different coming from reimagined or v4

**Comment by gri573** [comment]
I don't think it's brighter than reimagined, here's a comparison of the two:
reimagined:
![image](https://user-images.githubusercontent.com/66473137/218133083-4b7be0e4-2415-4735-8371-9bb8c6daa0ff.png)

rethinking voxels:
![image](https://user-images.githubusercontent.com/66473137/218132999-a763ea08-4e14-4418-9fa0-3215b09dd664.png)

if you are using the latest commit and have GI enabled, then that will make it brighter unless you are using the latest commit, where I reduced exposure with GI

**Comment by ZorkIsEmo** [comment]
![image](https://user-images.githubusercontent.com/112608837/218238058-94b07d69-befe-4322-8f93-ffda554c1c7d.png)

i feel like if you spawn into a desert and see this youd be blinded, this is the version downloaded from the modrinth link

![image](https://user-images.githubusercontent.com/112608837/218238096-1a9dec77-f1b2-420a-95f5-391c1ea8a986.png)

this is one where iv turned down how high the white tone can get

![image](https://user-images.githubusercontent.com/112608837/218238215-587aecfe-4f0f-4150-a192-1e07604adb1d.png)

crops from Stay True resource pack in default

![image](https://user-images.githubusercontent.com/112608837/218238225-6433d6e4-c1f0-414d-97c3-3cf243ee3cd7.png)

white tone down

**Comment by ZorkIsEmo** [comment]
didn't mean to close miss click

**Comment by ZorkIsEmo** [comment]
![image](https://user-images.githubusercontent.com/112608837/218238778-dc8be188-1df0-4b0a-9838-4717625b3f4d.png)

also vanilla comparison

![image](https://user-images.githubusercontent.com/112608837/218238881-819dd92c-0c69-4859-ae1e-06e650250f87.png)

![image](https://user-images.githubusercontent.com/112608837/218239155-182737db-2e5a-4fd0-90b5-7bd846a81963.png)

![image](https://user-images.githubusercontent.com/112608837/218239192-5365fd43-f6f2-45db-a407-1e63ef502331.png)
