### ISSUE TITLE
Crimson stem glowing part of texture very bright compared to light emitted

### ISSUE THREAD

**Issue by FeldrinH** [gri573/rethinking-voxels#74]
With crimson stem (probably a few other blocks as well, I did not try every block), by default it seems to emit a very faint light, but its texture has very bright glowing regions. It feels like these regions are too bright given how little light it emits. It would be nice if it was possible to make these glowing regions dimmer or disable the glowing regions entirely.

![2023-02-15_17 43 15](https://user-images.githubusercontent.com/5256211/219080007-d1c0d780-eff3-4c5f-af6d-51649137e582.png)

(Screenshot from Rethinking Voxels beta 17)

**Comment by gri573** [comment]
you can currently disable most glowing things by setting PBR support to basic in the shader pack settings (directly at the main shader settings menu). support for custom PBR resource packs will come with complementary reimagined v2.0, which will have PBR texture support, and which will be integrated with rethinking voxels. this is tracked in #41

**Comment by FeldrinH** [comment]
Setting PBR to basic would also disable many other material effects would it not?

**Comment by zndrmn** [comment]
The glowing gets brighter (and the color becomes more saturated) once stacked ontop of each other/in close proximity of other stems

**Comment by gri573** [comment]
> Setting PBR to basic would also disable many other material effects would it not?

Yes
