### ISSUE TITLE
Second layer of clouds behind sun

### ISSUE THREAD

**Issue by FeldrinH** [gri573/rethinking-voxels#75]
The second layer of clouds appears to be rendered behind the sun in Rethinking Voxels beta 17:

![2023-02-15_00 57 44](https://user-images.githubusercontent.com/5256211/219080735-2ffb4a11-53d1-4d3a-a368-a743eed6b853.png)

**Comment by gri573** [comment]
that's because clouds fade out if they are further away than some factor of the render distance. I'll see what I can do about it and hopefully upstream it to reimagined. it doesn't look that bad on my end though. did you increase the second cloud layer's altitude?

**Comment by FeldrinH** [comment]
The layer altitudes should be default. My settings:
![image](https://user-images.githubusercontent.com/5256211/219133559-1c55f99b-871b-4ac9-b0fa-29a2828b00e7.png)

**Comment by gri573** [comment]
this is fixed in reimagined now, and by consequence also in rethinking voxels
