### ISSUE TITLE
overall bug

### ISSUE THREAD

**Issue by Friicht** [gri573/rethinking-voxels#77]
When I put the shaders I have this.
![2023-02-17_22 16 12](https://user-images.githubusercontent.com/102788652/219794899-f57eaa6e-e4ac-4770-87b0-49dba223cb35.png)

**Comment by Friicht** [comment]
I using optifine in 1.19.2

**Comment by gri573** [comment]
that's rather broken... did it say something in chat about invalid programs?

**Comment by Friicht** [comment]
yes it say this
![2023-02-22_18 51 26](https://user-images.githubusercontent.com/102788652/220713365-1c1d0df3-7a71-4d71-a021-04ad92df171d.png)

**Comment by gri573** [comment]
in that case, there is probably more information about it in your latest.log file. you can find it in the "logs" subfolder of the minecraft folder after launching minecraft and trying to load the shader

**Comment by Friicht** [comment]
[latest.log](https://github.com/gri573/rethinking-voxels/files/10864221/latest.log)

**Comment by gri573** [comment]
The invalid program messages were generated when loading KappaPT, they were , not rethinking voxels. rethinking voxels seems to have loaded correctly according the log, but kappaPT seems to have failed compute shaders.
