### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by Maxi460** [gri573/rethinking-voxels#78]
I have a problem with global lighting. It feels like there is a radius around me in which the lighting is turned off, because the shader works well at a big distance (example below)
![2023-02-18_20 45 40](https://user-images.githubusercontent.com/48646199/219880883-a2836c73-d4c3-46fa-8b54-54364cc24055.png)
![2023-02-18_20 46 44](https://user-images.githubusercontent.com/48646199/219880886-c7352b71-06b5-4f1b-98fd-6653c131972d.png)

**Comment by gri573** [comment]
that's basically the lighting system not working at all. did you change any settings? can you post a log?

**Comment by Maxi460** [comment]
The problem was in the "Shadow quality" settings -- it was set to 0.5x when I set the 1x the shaders began to working correctly
![image](https://user-images.githubusercontent.com/48646199/220459192-a126da8c-1a79-4058-9837-d17b4fb20912.png)

**Comment by Maxi460** [comment]
The problem was in the "Shadow quality" settings -- it was set to 0.5x when I set the 1x the shaders began to working correctly
![image](https://user-images.githubusercontent.com/48646199/220459192-a126da8c-1a79-4058-9837-d17b4fb20912.png)

**Comment by gri573** [comment]
thank you, I will suggest this to other people with your problem
