### ISSUE TITLE
Entities are flicker

### ISSUE THREAD

**Issue by dnllbz** [gri573/rethinking-voxels#79]
Entities are flicker in low light if light block placed behind something

![javaw_TrrnV785VQ](https://user-images.githubusercontent.com/85390721/220169998-e516f94a-185e-4cb9-ab21-4f637b8ba8ea.jpg)
![image](https://user-images.githubusercontent.com/85390721/220170043-430837b2-f5ad-4e13-8fbd-38e727d10f27.png)
![image](https://user-images.githubusercontent.com/85390721/220170252-2e8b165e-27f2-46c7-a162-619ad02ef778.png)

**Comment by gri573** [comment]
it's better on the latest commit (and that's the best it'll get for now), will be in the next version
