### ISSUE TITLE
Incomplete held light colour mappings

### ISSUE THREAD

**Issue by gri573** [gri573/rethinking-voxels#82]
The system for adding held light colours is fully implemented, but it is missing most of the item IDs.
I'm too lazy to add them all. see shaders/item.properties for more information about how to add new held light colours.

**Comment by zndrmn** [comment]
So from my understanding, the itemID number is what determines what color it will output?
I'll proll work on this, it'll just take a while because the handheld lighting colors are not really 1:1 with blocklight colors with how they look in game.

**Comment by gri573** [comment]
yes, that's how it works. Thank you!

**Comment by zndrmn** [comment]
oh wow I completely forgot about his haha, sorry about that
