### ISSUE TITLE
`ShaderCompileException` Settings set to BasicLP + Global Illumination Off

### ISSUE THREAD

**Issue by zndrmn** [gri573/rethinking-voxels#83]
Logs [latest.log](https://gist.github.com/zndrmn/48b682dbd772df92da939b5a9d565326#file-latest-log)
Shader Settings [ rethinking-voxels [ main.246 c3365c2 ].zip.txt](https://gist.github.com/zndrmn/81bb8ea4aff4981b378e68a9e298afc3#file-rethinking-voxels-main-246-c3365c2-zip-txt)

**Comment by gri573** [comment]
fixed on `d9a6fd1`
