### ISSUE TITLE
Brightness discrepancy between BasicLP + Global Illumination On/Off

### ISSUE THREAD

**Issue by zndrmn** [gri573/rethinking-voxels#84]
Just so you know this first screenshot is from commit: [`a2d88a1`](https://github.com/gri573/rethinking-voxels/commit/a2d88a1a0201d818efb47af3fcc9ec57730743c7) second screenshot is from commit: [`c3365c2`](https://github.com/gri573/rethinking-voxels/commit/c3365c234edd9e20199634b10513a2f4cc414bbc) 
because [`c3365c2`](https://github.com/gri573/rethinking-voxels/commit/c3365c234edd9e20199634b10513a2f4cc414bbc) fails to compile #83

BasicLP + Global Illumination **On**

![2023-02-22_14 20 12](https://user-images.githubusercontent.com/77690119/220753158-db0445fa-0caf-4667-97cc-b001bc9c01d2.png)

BasicLP + Global Illumination **Off**

![2023-02-22_14 20 21](https://user-images.githubusercontent.com/77690119/220754589-ed77a1b5-6614-4571-b768-aa1216c225ae.png)

**Comment by gri573** [comment]
noted, will rebalance

**Comment by gri573** [comment]
the current system is now gone, so this problem is gone with it
