### ISSUE TITLE
Conduit & Brewing Stand (and more) can't self-lit...

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#89]
Fabric, latest 27/2/2023 github commit

Blocks which will end up with not nice looking lighting under/around/on themselves:

-Conduit
-Brewing Stand
-Camp Fire (Not Soul version (Soul have a different light issue which flicker brither but is kinda random))
-Dragon Egg

https://youtu.be/S8H8gIUaxec

![2023-03-01_19 01 18](https://user-images.githubusercontent.com/29926123/222314779-17224548-aca1-42de-b268-06972d57dcca.png)

![2023-03-01_21 27 16](https://user-images.githubusercontent.com/29926123/222315265-dbecad32-d8c7-4ad8-958f-1a4c11813da6.png)

**Comment by gri573** [comment]
actually, I don't want to close this until it is in a published version
