### ISSUE TITLE
shadow not normal

### ISSUE THREAD

**Issue by z78966789** [gri573/rethinking-voxels#9]
Minecraft version: 1.18.2
shader version: last
shader config: default
Iris version: 1.4.5
Sodium version: 0.4.1

![2022-12-22_16 44 03](https://user-images.githubusercontent.com/111133655/209098628-5254609c-e7c9-44ce-aaad-caaa29765827.png)
![2022-12-22_16 50 28](https://user-images.githubusercontent.com/111133655/209097675-19d20213-c1a4-46ea-9988-26d6d983ee7a.png)
Can repair?

**Comment by gri573** [comment]
the scene shown in the lower image is working as intended, the upper one is not easily fixable, although it will eventually be improved
