### ISSUE TITLE
Lava has glitched light artifact & lava, camp fire, fire have aggressive light flicker

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#90]
Fabric, latest 27/2/2023 github commit

As described, Lava has glitched light artifact while using **Advanced** setting.

https://youtu.be/fzbmg-yWAPM

Basic Setting:
& Lava, camp fire and fire have aggressive light flicker.
*May i include there's some green tint going on with lava/fire

https://youtu.be/IoPRbDiSeY4

**Comment by gri573** [comment]
The fire, camp fire flickering with advanced light propagation are intended, but they are just exaggerated by your recource pack. you can enable "override fire color" in main lighting settings -> block light colors -> fire. the rest is an issue that I am somewhat aware of, but it didn't look that bad on my end yet (probably also exaggerated by your RP). I will see what I can do about it

**Comment by TwinShards** [comment]
My texture pack only change the fire, camp & lava are still vanilla texture.
You right i verified on my end and my fire texture goes indeed make it more violent than using vanilla texture

I don't know how much work this would require but what if you were handling the light color/flicker based by the block's ID instead of it's texture, color and shape, couldn't this make any texture pack become consistant compared to vanilla?

**Comment by DarianLStephens** [comment]
That's what the 'override fire color' option is meant to do. You can override other colors, as well, like Lava.
I personally quite like that it changes based on the actual color, and would be sad to see it removed.

**Comment by gri573** [comment]
I won't do light flickering other than using the texture-based method, as that would be annoying to implement. I might tweak the light colour detection a little in the future
