### ISSUE TITLE
Bright spots below mobs

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#91]
Fabric, latest 5ff62a3 12/3/2023 github commit

Using...
Default Setting
BUT Maxed GI Strenght, (transparent issue fixed), Bright spots below mobs present

https://youtu.be/FeIWJhEfrqg

**Comment by gri573** [comment]
I can't reproduce the lighting at mobs' feet issue

**Comment by TwinShards** [comment]
> I can't reproduce the lighting at mobs' feet issue

I believe you may consider this (bright spots below mobs) as fix.

After fixing "semi-transparent" issue the bright spots are still visible but so subtle that you would probably not notice them without seeking to see it happen, that, OR the (VERY) bright spots like shown in the video are only visible under very specific condition

**Comment by TwinShards** [comment]
> I can't reproduce the lighting at mobs' feet issue

With everything else default setting from latest commit (5ff62a3 23/3/12)

Max out GI Strenght

(Updated my bug report to reflect current state)

**Comment by gri573** [comment]
this is gone in the rewrite because GI is gone
