### ISSUE TITLE
Voxel Volume (Advanced) cause entitie to visually vanish

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#92]
Fabric, latest 27/2/2023 github commit

Also happen with VV Height 64 but mobs have to be further away...
(Also can change the distance for this issue to happen with VV Size)

(Also Block Entity when you place/remove them without moving your POV)

https://youtu.be/wTcbyjRD8QM

**Comment by gri573** [comment]
that is possibly a problem with complementary reimagined itself. I have tried to find its cause, but failed so far

**Comment by gri573** [comment]
this is much less apparent in the latest version, you can disable entity culling in sodium's settings to fix it completely
