### ISSUE TITLE
Water is brighter than your mom (jk)

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#93]
Fabric, latest 27/2/2023 github commit

Ok sorry i couldn't resist making a title like this.

For some reason changing the setting
Basic. Light Prop. Settings > **"Translucent Light Conduction:"** above 1 will cause the water to become bright blue if there is any light source hitting it (including sun/moon)

*I believe GI Strenght is the main issue as setting his value to 0 will also solve the problem and other light issue
(GI Strenght above 3 will cause other kind of light issue (while in advanced especially)

https://youtu.be/CjBJ1QxD6ZQ

**Comment by gri573** [comment]
that is known and can't be fixed. there is even a disclaimer about it in the setting's tooltip
