### ISSUE TITLE
TNT/GlowSquid bad lighting

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#94]
Fabric, latest 27/2/2023 github commit

while using Advanced Lighting, TNT fail to lit up some location that it should lit up.
while basic is better, it seems entity are limited to a block-by-block lighting instead of being accurate to decimal.

https://youtu.be/iZmlYLihzZI

**Comment by gri573** [comment]
Entity voxelisation is pretty difficult to do, so I don't know if I can fix it, but I'll give it a go.

**Comment by TwinShards** [comment]
Over all:
Lit TNT Seems to be much smoother. Lighting in air/on ground & Fully underwater is as good as you can do it (i think) 😉
However
-TNT's lighting has difficulty lighting up flowing water
-GlowSquid is still the same mess as you didn't take a look at them. (I guess applying the current fix for TNT on glowsquid Should do the trick perfectly)

**Comment by gri573** [comment]
this should be fixed with accurate RT enabled, and I don't think I will fully fix it with voxel RT
