### ISSUE TITLE
in 3rd perspective, shader behavior is tie to the camera

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#96]
If you hold a light source, the light come out of the camera's location instead of the player's location.
Same goes for water interaction.

**Comment by gri573** [comment]
I always assumed that was not fixable, but it turns out that it is, although only on iris

**Comment by TwinShards** [comment]
Hold up, I should probably move this issue to Compementary instead. Just checked and this issue is with their shader

**Comment by gri573** [comment]
this is now fixed
