### ISSUE TITLE
Reimagined Cloud have artifact while looking at sun/moon

### ISSUE THREAD

**Issue by TwinShards** [gri573/rethinking-voxels#97]
Fabric, latest 27/2/2023 github commit

It appear that clouds have some strange artifact of Fantasy setting casting on reimagined clouds

https://youtu.be/UnbBp8a7Qb8

**Comment by gri573** [comment]
yes, I just never got around to updating the cloud calculation to use the new shadow map rather than the original one, so shadows on clouds are just invalid at this point

**Comment by gri573** [comment]
this is now fixed
